### ISSUE TITLE
[EPIC] Discussions in DCAR

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#10023]
This quarter (Jan-Mar 2024) we’ll be working on implementing discussions in DCAR. We hope will reduce the amount of platform-specific logic in favour of a unified approach. We may also use this as an opportunity to simpliying existing the code and fix bugs.

Rough tasks that need addressing

- How does sign-in works with Bridget?
- How do fetch requests work in WebViews?
- How is saving preferences handled?
- How should discussion behave when offline?

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/9667
- [ ] https://github.com/guardian/dotcom-rendering/issues/10056
```

```[tasklist]
### Known Bugs
- [ ] another bug that comes up every so often is anything after a semi-colon in a post going missing
- [ ] few people asking why we don't support emojis
- [ ] https://github.com/guardian/dotcom-rendering/issues/4741
- [ ] https://github.com/guardian/dotcom-rendering/issues/8955
- [ ] https://github.com/guardian/dotcom-rendering/issues/9881
```

**Comment by alinaboghiu** [comment]
From Jame's original epic ticket: 

"Discussion in web and Apps differs in that in Apps post endpoints interact with the native layer directly as that's where the user information is know. e.g. postComment or reportAbuse

There has been some work to account for this by [using callbacks on the CommentContainer](https://github.com/guardian/dotcom-rendering/blob/2926f9836accef42a9130b7fb61ba7ba2966280b/dotcom-rendering/src/components/Discussion/CommentContainer.tsx#L29-L37).

When migrating [discussion-rendering](https://github.com/guardian/discussion-rendering) we had opted for expediency to not always follow this pattern, so will need to find those interactions that speak to the discussion API directly and port them over to the paradigm above.

We might need to work with Apps here to help create any endpoints that don't exist."

**Comment by mxdvl** [comment]
Duplicate of #8745
