### ISSUE TITLE
Remove decidePalette

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#10045]
```[tasklist]
### Tasks
- [x] Remove decidePalette from Card components
- [x] Remove decidePalette from Youtube components
- [x] Remove decidePalette from ArticleHeadline
- [x] Remove decidePalette from ArticleLastUpdated
- [x] Remove decidePalette from CardHeadline
- [x] Remove decidePalette from CricketScoreboard
- [x] Remove decidePalette from DesignTag
- [x] Remove decidePalette from FilterLink
- [x] Remove decidePalette from ImageComponent
- [x] Remove decidePalette from LightboxCaption
- [x] Remove decidePalette from MostViewedFooterData
- [x] Remove decidePalette from NumberedTitleBlockComponent
- [x] Remove decidePalette from PinnedPost
- [x] Remove decidePalette from SendAMessage
- [x] Remove decidePalette from SupportingContent
- [x] Remove decidePalette from TopicFilterBank
- [x] Remove decidePalette from Treats
- [ ] https://github.com/guardian/dotcom-rendering/pull/12201
- [ ] https://github.com/guardian/dotcom-rendering/issues/12988
- [ ] https://github.com/guardian/dotcom-rendering/issues/12989
- [ ] https://github.com/guardian/dotcom-rendering/issues/12990
```
