### ISSUE TITLE
Use `@guardian/libs` storage everywhere

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#10052]
Since #9994, we want to prevent direct usage of `localStorage` and `sessionStorage`. This will help with our audit #8838.

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/pull/10047
- [ ] https://github.com/guardian/dotcom-rendering/pull/10048
- [ ] https://github.com/guardian/dotcom-rendering/issues/10055
- [x] https://github.com/guardian/dotcom-rendering/issues/10078
- [ ] https://github.com/guardian/dotcom-rendering/issues/10081
- [ ] https://github.com/guardian/dotcom-rendering/issues/10074
- [ ] https://github.com/guardian/dotcom-rendering/issues/10053
- [ ] https://github.com/guardian/dotcom-rendering/issues/10121
- [ ] https://github.com/guardian/dotcom-rendering/issues/10106
- [ ] https://github.com/guardian/dotcom-rendering/issues/10100
```
