### ISSUE TITLE
[Epic] Descendants of `DiscussionContainer` are controlled components

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#10056]
Make all the descendants of DiscussionContainer controlled components – see [React Docs Deep Dive](https://react.dev/learn/sharing-state-between-components#controlled-and-uncontrolled-components).

```mermaid
flowchart TB
    %% DiscussionContainer.importable -.-> Placeholder
    DiscussionContainer.importable --> DiscussionWhenSignedIn & Discussion
    DiscussionWhenSignedIn --> Discussion
    Discussion --> SignedInAs & Comments
    %% Discussion -.-> Hide & Button & SvgPlus
    Comments --> TopPicks & Filters & Pagination & CommentContainer & CommentForm & LoadingComments
    CommentContainer --> Comment & CommentReplyPreview & CommentForm
    CommentForm --> FirstCommentWelcome & Preview
```

In order to make sense of this, we need to unify all duplicated state from components, and pass callbacks to handle events. 

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/10224
- [ ] https://github.com/guardian/dotcom-rendering/issues/10225
- [ ] https://github.com/guardian/dotcom-rendering/issues/10226
- [ ] https://github.com/guardian/dotcom-rendering/issues/10227
- [ ] https://github.com/guardian/dotcom-rendering/issues/10228
- [ ] https://github.com/guardian/dotcom-rendering/issues/10229
- [ ] https://github.com/guardian/dotcom-rendering/issues/10230
- [ ] https://github.com/guardian/dotcom-rendering/issues/10297
```
