### ISSUE TITLE
`csnx` → `dotcom-rendering`

### ISSUE THREAD

**Issue by sndrs** [guardian/dotcom-rendering#10108]
Following https://github.com/guardian/dotcom-rendering/discussions/9865, @guardian/client-side-infra plan to move the libs that currently live in https://github.com/guardian/csnx to this repo.

As part of this, CSTI will also start to take a more active repo maintaining role.

This issue tracks the changes to make that happen.

```[tasklist]
### Tasks
- [x] raise RFC in https://github.com/guardian/dotcom-rendering/discussions
- [x] agreement between @guardian/client-side-infra and @guardian/dotcom-platform on proceeding (or not)
- [ ] add CSTI code ownership roles in `dotcom-rendering`
- [ ] add and directly consume `@guardian/prettier` in `dotcom-rendering`
- [ ] add changesets and start publishing `@guardian/prettier` from `dotcom-rendering`
- [ ] remove `@guardian/prettier` from `csnx`
- [ ] enable Nx's remote computation caching in `dotcom-rendering` and apply it to `@guardian/prettier` package
- [ ] enable remote computation caching for DCR and AR
- [ ] rename `guardian/dotcom-rendering` repo?
- [ ] move `@guardian/tsconfig` to `dotcom-rendering`
- [ ] move `@guardian/libs` to `dotcom-rendering`
- [ ] move `@guardian/source-foundations` to `dotcom-rendering`
- [ ] move `@guardian/source-react-components` to `dotcom-rendering`
- [ ] move `@guardian/source-react-components-development-kitchen` to `dotcom-rendering`
- [ ] move `@guardian/eslint-plugin-source-foundations` to `dotcom-rendering`
- [ ] move `@guardian/eslint-plugin-source-react-components` to `dotcom-rendering`
- [ ] move `@guardian/ab-core` to `dotcom-rendering`
- [ ] move `@guardian/ab-react` to `dotcom-rendering`
- [ ] move `@guardian/browserslist-config` to `dotcom-rendering`
- [ ] move `@guardian/core-web-vitals` to `dotcom-rendering`
- [ ] move `@guardian/eslint-config` to `dotcom-rendering`
- [ ] move `@guardian/eslint-config-typescript` to `dotcom-rendering`
- [ ] move `@guardian/identity-auth` to `dotcom-rendering`
- [ ] move `@guardian/identity-auth-frontend` to `dotcom-rendering`
- [ ] move `@guardian/newsletter-types` to `dotcom-rendering`
- [ ] archive `csnx`
```

**Comment by sndrs** [comment]
dupe of #10108
