### ISSUE TITLE
Scaling optimisations post article-rendering launch

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#10273]
There are a number of tweaks we should do to follow up after splitting the DCR traffic between articles and other traffic. These could be considered alongside further splitting of DCR traffic and shouldn't be considered a blocker.

The step scaling policy is too rigid at the moment and does not allow for different environments. We could adjust the instance type on the CODE environment to be similar to production, or [adjust the scaling policy so that we can tailor it to different needs](https://github.com/guardian/dotcom-rendering/pull/10263), or both.

We could also consider moving to target tracking scaling instead of step scaling, and scaling on different metrics rather than just latency.

The number of instances running, and available to scale to, in both apps is too high for our needs so we should reduce to more sensible numbers.

```[tasklist]
### Tasks
- [x] Reduce the maximum number of instances in `rendering` (120 is a lot)
- [x] Reduce the minimum number of instances in `rendering` since we are handing far fewer requests now that `article-rendering` handles most of the traffic
- [x] [Reduce the minumum number of instances in `article-rendering`](https://github.com/guardian/dotcom-rendering/pull/10261)
```
