### ISSUE TITLE
Implement Discussion API On iOS

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#10326]
```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/10639
- [ ] Implement comment
- [ ] Implement reply
- [ ] https://github.com/guardian/dotcom-rendering/issues/10737
- [ ] https://github.com/guardian/dotcom-rendering/issues/10776
- [x] Implement Sign in and isSignedIn on iOS
```

**Comment by mxdvl** [comment]
Update tomorrow (Feb 6) after pairing with iOS native dev

**Comment by georgeblahblah** [comment]
https://github.com/guardian/ios-live/pull/7568
