### ISSUE TITLE
Scheduled Subnav changes - next change due 25 May

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#10490]
Some subnav changes scheduled at the bottom of this doc: 

https://docs.google.com/document/d/1jbyE7inWvPDIK2xsxaX3cJZf3BVdQxFUtE-3Hp9CnxQ/edit#heading=h.fcc0pi9et5u3

```[tasklist]
### Tasks
- [x] Add Super Bowl - 5 Feb
- [x] Remove Super Bowl - 13 Feb
- [x] Add Oscars - 5 Mar
- [x] Remove Oscars - 12 Mar
- [x] Add solar eclipse - 5 Apr
- [x] Remove solar eclipse - 9 Apr
- [ ] https://github.com/guardian/dotcom-rendering/issues/11460
- [ ] Add Paris Summer Olympics - 1 Jul
- [ ] Remove Paris Summer Olympics - 15 Aug
- [ ] Add Cop29 - 4 Nov
- [ ] Remove Cop29 - 26 Nov
```

**Comment by alinaboghiu** [comment]
@mxdvl would you mind adding Solar eclipese as part of rota please? 
They confirmed it should go under News after Wellness (US edition only)
