### ISSUE TITLE
Implement New Article Structure

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#10491]
Key takeaways, timelines and Q&As. In collaboration with Content Production.

https://www.figma.com/file/xPr2tZZger7pszcO075tAQ/New-Formats---April-23?type=design&node-id=3610%3A51261&mode=design&t=V7lJKJB8vgZzDd2t-1

```[tasklist]
### Tasks
- [ ] #10741
- [ ] https://github.com/guardian/dotcom-rendering/issues/10794
- [ ] https://github.com/guardian/dotcom-rendering/issues/10791
- [ ] https://github.com/guardian/dotcom-rendering/issues/10841
- [ ] https://github.com/guardian/dotcom-rendering/issues/10865
- [ ] https://github.com/guardian/dotcom-rendering/issues/10866
- [ ] https://github.com/guardian/dotcom-rendering/issues/10867
- [ ] https://github.com/guardian/dotcom-rendering/issues/10852
- [ ] https://github.com/guardian/dotcom-rendering/issues/10902
- [ ] https://github.com/guardian/dotcom-rendering/issues/10915
- [ ] https://github.com/guardian/dotcom-rendering/issues/10853
- [ ] https://github.com/guardian/dotcom-rendering/issues/10854
- [ ] https://github.com/guardian/dotcom-rendering/issues/10963
- [ ] #10743
- [ ] #10742
- [ ] https://github.com/guardian/dotcom-rendering/issues/10856
- [ ] https://github.com/guardian/dotcom-rendering/issues/10964
- [ ] https://github.com/guardian/dotcom-rendering/issues/10868
- [ ] https://github.com/guardian/dotcom-rendering/issues/10869
- [ ] https://github.com/guardian/dotcom-rendering/issues/10965
- [ ] https://github.com/guardian/dotcom-rendering/issues/10769
- [ ] Flatten Timelines For Live Apps
- [x] Flatten Timelines For Editions
- [ ] https://github.com/guardian/dotcom-rendering/issues/11083
```
