### ISSUE TITLE
Create Bridget API for discussion

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#10544]
* https://github.com/guardian/dotcom-rendering/pull/10493
introduced a stub of what this API might look like. This ticket is to: 

1. Flesh out the methods:
https://github.com/guardian/dotcom-rendering/blob/f72ed3fa9be84bee4cc07524d1969ec305c6da54/dotcom-rendering/src/components/DiscussionApps.importable.tsx#L10-L31

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/10668
- [ ] https://github.com/guardian/dotcom-rendering/issues/10670
- [ ] https://github.com/guardian/dotcom-rendering/issues/10671
- [ ] https://github.com/guardian/dotcom-rendering/issues/10672
- [ ] https://github.com/guardian/dotcom-rendering/issues/10673
- [ ] https://github.com/guardian/dotcom-rendering/issues/10669
- [ ] https://github.com/guardian/dotcom-rendering/issues/10909
- [ ] https://github.com/guardian/dotcom-rendering/issues/11168
```

2. Add the API to [bridget](https://github.com/guardian/bridget)

**Comment by ioannakok** [comment]
Re adding the API to Bridget, we have a draft PR: https://github.com/guardian/bridget/pull/111

**Comment by alinaboghiu** [comment]
@ioannakok has a draft PR she will add to this ticket

**Comment by ioannakok** [comment]
Draft PR to implement Bridget methods: https://github.com/guardian/dotcom-rendering/pull/10858

**Comment by mxdvl** [comment]
Complete! 🎉
