### ISSUE TITLE
Upgrade riffraff actions version

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#10600]
We need to upgrade our repos to use v4 of `actions-riff-raff`.

This is a breaking change and will require us to provide a `roleArn` field to the GH action.
There's an example PR of the upgrade here: https://github.com/guardian/service-catalogue/pull/794

[See email thread here for more information](https://groups.google.com/a/guardian.co.uk/g/engineering/c/neUQqs_AOLE/m/o3xwPBmpAAAJ)

See [dashboard](https://metrics.gutools.co.uk/d/b7f891a9-4fbe-4144-b78a-077e262fb0e6/repos-to-update-actions-riff-raff-version-for?orgId=1) for which repos we need to update
```[tasklist]
### Tasks
- [x] Update dotcom-rendering to use `actions-riff-raff@v4`
- [x] Update frontend to use `actions-riff-raff@v4`
- [x] Update platform to use `actions-riff-raff@v4` https://github.com/guardian/platform/issues/1578
- [x] Update fastly-edge-cache to use `actions-riff-raff@v4`
- [x] Update fonts to use `actions-riff-raff@v4` https://github.com/guardian/fonts/issues/27
- [x] Update fastly-image-service to use `actions-riff-raff@v4`
- [x] Update domains-platform to use `actions-riff-raff@v4`
- [x] Update frontend-lambda to use `actions-riff-raff@v4`
- [x] Update about-us to use `actions-riff-raff@v4`
- [x] Update email-rendering to use `actions-riff-raff@v4`
- [x] Update dotcom-onion-platform to use `actions-riff-raff@v4`
- [x] Update message-us-lambda to use `actions-riff-raff@v4` - No longer required as message us feature is due to be removed
```
