### ISSUE TITLE
Implement authentication checks on DCAR

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#10785]
DCAR articles do not yet take into account a users authentication status. However, the platform now needs to make decisions based on if a user is signed in or not. This is so that we can a) update the UI accordingly, and b) perform authenticated user actions such as posting comments. 

This change will require work in four areas: 

- DCR support
- Bridget support
- Native iOS support 
- Native Android support

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/10909
- [ ] https://github.com/guardian/dotcom-rendering/issues/10786
- [ ] https://github.com/guardian/dotcom-rendering/issues/10787
- [ ] https://github.com/guardian/dotcom-rendering/issues/10900
```
