### ISSUE TITLE
Implement Timeline Element Design

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#10869]
Still to do:

```[tasklist]
### Tasks
- [x] Add a story with a thumbnail main media
- [x] Add a story with a video
- [x] Add labels
- [ ] https://github.com/guardian/dotcom-rendering/issues/11145
- [ ] https://github.com/guardian/dotcom-rendering/issues/11125
- [ ] https://github.com/guardian/dotcom-rendering/issues/11109
- [ ] https://github.com/guardian/dotcom-rendering/issues/11118
- [ ] https://github.com/guardian/dotcom-rendering/issues/11170
- [ ] https://github.com/guardian/dotcom-rendering/issues/11208
- [x] Better name for `getNestedArticleElement`?
- [ ] https://github.com/guardian/dotcom-rendering/issues/11150
- [ ] https://github.com/guardian/dotcom-rendering/issues/11248
```
