### ISSUE TITLE
[Epic]: Build Election Tracker For UK Local Elections

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#11006]
The Visuals team have asked us to help with building election trackers for the UK local elections: polling day **2nd May 2024**

**Data** 
"In terms of the data source, here is a [link to data](https://interactive.guim.co.uk/2023/05/local-elex-data/production/data/local/state-of-parties.json%60) from last year that will give you a good idea of the structure to build to."

**Designs**
https://www.figma.com/file/QVdsR1o0jlGYWTXwSWu7da/Election-snaps?type=design&node-id=0%3A1&mode=design&t=PBTlfr9o7pIgra28-1

**Planning Doc**
https://docs.google.com/document/d/18l7oFeEew1ytmA1YQU8u-rDnFHyVVvwuZ81_57h-Qqg/edit

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/11128
- [x] Clarify some points with Seán and Ashley
- [x] Summarise the model that describes the shape of the data we're working with
- [x] Summarise how frontend handles snap links
- [x] Decide on an architecture approach
- [x] Decide how we're going to retrieve the data
- [x] Test on apps (maybe ask the Apps team for help)
- [x] Test on web
- [ ] https://github.com/guardian/dotcom-rendering/issues/11322
- [ ] https://github.com/guardian/dotcom-rendering/issues/11325
- [ ] https://github.com/guardian/dotcom-rendering/issues/11323
- [ ] https://github.com/guardian/dotcom-rendering/issues/11324
- [ ] https://github.com/guardian/dotcom-rendering/issues/11326
- [ ] https://github.com/guardian/dotcom-rendering/issues/11335
- [ ] https://github.com/guardian/dotcom-rendering/issues/11336
- [ ] https://github.com/guardian/dotcom-rendering/issues/11370
```

**Comment by alinaboghiu** [comment]
@HarryFischer I think this Figma link is broken? 👆

**Comment by HarryFischer** [comment]
Updated it @alinaboghiu
