### ISSUE TITLE
[Epic]: Address AWS Trusted Advisor recommendations 

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#11097]
<img width="730" alt="Screenshot 2024-04-09 at 08 45 41" src="https://github.com/guardian/dotcom-rendering/assets/1229808/5cec64af-26a7-4716-b18b-7928bb60ebc6">

```[tasklist]
### Security
- [ ] Lambdas using deprecated runtime
- [ ] Instances using public IPv4 addresses
- [ ] Launch templates with public IPs
- [ ] Use Metadata Service v2
- [ ] Security Group unrestricted access
- [ ] Default VPC security group should not allow inbound/outbound traffic
- [ ] https://github.com/guardian/platform/issues/1504

```

```[tasklist]
### Cost
- [ ] unassociated elastic IP: 	34.252.75.132
- [ ] Low Utilization Amazon EC2 Instances: change to t2.nano or cheapest
```
