### ISSUE TITLE
[Epic]: Build Election Tracker For UK General Election 2024

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#11111]
See also #11006.

```[tasklist]
### Tasks
- [x] Gather Requirements From Visuals and Editorial
- [ ] https://github.com/guardian/dotcom-rendering/issues/11727
- [x] Test Trackers With Different Data
- [ ] https://github.com/guardian/dotcom-rendering/issues/11774
- [ ] https://github.com/guardian/dotcom-rendering/issues/11731
- [x] Round-up meeting with Visuals and digi eds to go over everything
- [x] Send snap links to digi eds and CP
- [ ] https://github.com/guardian/dotcom-rendering/issues/11729
- [ ] https://github.com/guardian/dotcom-rendering/issues/11606
- [ ] https://github.com/guardian/dotcom-rendering/issues/11607
```
