### ISSUE TITLE
[Epic]: Build Election Tracker For EU Elections 2024

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#11110]
**When:** 6th-9th June 2024

See also #11006.

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/11311
- [ ] https://github.com/guardian/dotcom-rendering/issues/11388
- [ ] https://github.com/guardian/dotcom-rendering/issues/11461
- [ ] https://github.com/guardian/dotcom-rendering/issues/11390
- [x] Test the atom on dotcom
- [x] Test the atom on apps
- [ ] https://github.com/guardian/dotcom-rendering/issues/11548
- [ ] https://github.com/guardian/dotcom-rendering/issues/11544
- [ ] https://github.com/guardian/dotcom-rendering/issues/11545
- [ ] https://github.com/guardian/dotcom-rendering/issues/11543
- [ ] https://github.com/guardian/dotcom-rendering/issues/11542
```

**Comment by shesah** [comment]
an outline of election-night times from the EP press service, which has been sent to us all in Brussels.
I'll add in more details when I get them.

a first set of available national estimates to be published around 18.15 CEST,

the first projection of the new Parliament, expected around 20.15-20.30 CEST (indicative time), also based on national estimates, and

the first provisional results from some EU member states with estimates for the rest as well as a second seat projection, to be published at around 23.15-23.30 CEST (indicative time).

Updated projections will follow, as Parliament’s services receive information from national authorities. The last updated projection is expected at around 01.00 CEST on Monday 10 June.

A detailed schedule of estimates and provisional results will be published in the coming days.
