### ISSUE TITLE
Gather Requirements From Visuals And Editorial

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#11388]
```[tasklist]
### Tasks
- [x] Find out what the data model will look like
- [x] Find out what the political groups and their IDs will be
- [x] Find out what the container palettes will be
- [x] Verify in which fronts the tracker will appear
- [x] Find out when the tracker will be added and for how long
- [x] Should the results be sorted?
```
