### ISSUE TITLE
[Epic] Tag link test: build components

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#11431]
```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/11425
- [ ] https://github.com/guardian/dotcom-rendering/issues/11432
- [x] Tag link test: Determine data source of tag link  - we might be able to hardcode this for the first euro test
```

```[tasklist]
### Tasks
```
