### ISSUE TITLE
Build the UK GE 2024 Exit Poll Tracker

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#11606]
Static display from 8pm on election day until the results start trickling in
```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/11747
- [ ] https://github.com/guardian/dotcom-rendering/issues/11750
- [ ] https://github.com/guardian/dotcom-rendering/issues/11751
- [ ] https://github.com/guardian/dotcom-rendering/issues/11753
- [ ] https://github.com/guardian/dotcom-rendering/issues/11756
- [ ] https://github.com/guardian/dotcom-rendering/issues/11764
- [ ] https://github.com/guardian/dotcom-rendering/issues/11766
- [ ] https://github.com/guardian/dotcom-rendering/issues/11769
- [ ] https://github.com/guardian/dotcom-rendering/issues/11767
- [ ] https://github.com/guardian/dotcom-rendering/issues/11771
- [ ] https://github.com/guardian/dotcom-rendering/issues/11765
- [ ] https://github.com/guardian/dotcom-rendering/issues/11770
```

**Comment by mxdvl** [comment]
See implementation: https://github.com/guardian/interactives/pull/1666

**Comment by georgeblahblah** [comment]
Closing as all subtasks completed. 😁 

![IMG_9798](https://github.com/guardian/dotcom-rendering/assets/705427/7ccb03d0-379a-4abf-8f72-928c1dbc6b6c)
