### ISSUE TITLE
Build the UK GE 2024 Results Tracker

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#11607]
```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/11620
- [ ] https://github.com/guardian/dotcom-rendering/issues/11621
- [ ] https://github.com/guardian/dotcom-rendering/issues/11622
- [ ] https://github.com/guardian/dotcom-rendering/issues/11628
- [ ] https://github.com/guardian/dotcom-rendering/issues/11623
- [ ] https://github.com/guardian/dotcom-rendering/issues/11625
- [ ] https://github.com/guardian/dotcom-rendering/issues/11627
- [ ] https://github.com/guardian/dotcom-rendering/issues/11626
- [ ] https://github.com/guardian/dotcom-rendering/issues/11624
- [ ] https://github.com/guardian/dotcom-rendering/issues/11716
- [ ] https://github.com/guardian/dotcom-rendering/issues/11681
- [ ] https://github.com/guardian/dotcom-rendering/issues/11718
- [ ] https://github.com/guardian/dotcom-rendering/issues/11734
- [ ] https://github.com/guardian/dotcom-rendering/issues/11736
- [ ] https://github.com/guardian/dotcom-rendering/issues/11739
- [ ] https://github.com/guardian/dotcom-rendering/issues/11737
- [ ] https://github.com/guardian/dotcom-rendering/issues/11682
- [ ] https://github.com/guardian/dotcom-rendering/issues/11768
- [ ] https://github.com/guardian/dotcom-rendering/issues/11684
- [ ] https://github.com/guardian/dotcom-rendering/issues/11683
```
