### ISSUE TITLE
Capture web vitals attribution data

### ISSUE THREAD

**Issue by abeddow91** [guardian/dotcom-rendering#11688]
Use the events collector to send more accurate attribution data for our web vitals

```[tasklist]
### Tasks
- [x] Add a  new route for web vitals in the event collector
- [x] Create a new temporary table - see https://github.com/guardian/data-platform-models/pull/5270 for example set up
- [ ] List Nophan in the CMP for Web and Apps
- [ ] Update web vital package in csnx to include attribution
- [ ] bump core-web-vitals in DCR
- [ ] validate numbers against exisiting logging
```
