### ISSUE TITLE
Fix bugs from design review

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#11718]
```[tasklist]
### Tasks
- [x] xxx/650 seats declared should be bold
- [x] "326 seats for majority" line is transparent with fewer data
- [x] Top-padding: 4px
- [x] 320px breakpoint it doesn’t fit. Make font smaller
- [x] 90% line-height on .seats
- [x] Add z-index in the majority line
- [x] Dark modeLab / Con should be same colour as lines above
- [x] Line at the top should not be so thick
```

**Comment by ioannakok** [comment]
* https://github.com/guardian/interactives/pull/1697
