### ISSUE TITLE
Preparation for the election night

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#11760]
```[tasklist]
### Tasks
- [ ] Decide on the levels of scaling
- [ ] Not code freeze but code cooldown: No big PRs, WebX carefully reviews other teams PRs
- [ ] No Fastly / Router changes
```

https://docs.google.com/document/d/128edB58h4S_cgaJdKT21nZ_1oVUQLOy_6HLCco1cHVw/edit#heading=h.lccbdwgx638z

**Comment by ioannakok** [comment]
Had a meeting. This is what we discussed: https://docs.google.com/document/d/128edB58h4S_cgaJdKT21nZ_1oVUQLOy_6HLCco1cHVw/edit#heading=h.lccbdwgx638z
