### ISSUE TITLE
Consolidate Alerts

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#11825]
Some of our alerts overlap, can we simplify?

```[tasklist]
### Tasks
- [ ] Do we need both Pagerduty and DevX alerts?
- [ ] Do we need alerts on every scaling event?
- [ ] Can the alert information be more readable?
```
