### ISSUE TITLE
Get dependabot checks green automatically

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#3882]
Currently there are two issues stopping us from getting green checks when @dependabot opens a dependency bump chore PR.

**Snyk**
- [ ] Needs access to a env var SNYK_TOKEN
- [ ] Can't run @dependabot PRs on push as that runs in `read` mode. [See the error here](https://github.com/guardian/dotcom-rendering/runs/4950955741?check_suite_focus=true#step:6:52).

**Chromatic**
- [ ] Needs access to `CHROMATIC_APP_CODE` env var

See [dependabot secrets](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/managing-encrypted-secrets-for-dependabot) for the env vars.

## TODO
- [ ] remove `CHROMATIC_APP_CODE` once there are no PRs reliant on it see: https://github.com/guardian/dotcom-rendering/pull/3898
