### ISSUE TITLE
[Epic]: Stop using teamcity

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#5125]
At the end of this Q2 the DevX team have a desire to turn off [TeamCity](https://teamcity.gutools.co.uk/), in favour of using GitHub Actions.

List of repos that we should migrate: https://docs.google.com/spreadsheets/d/1DWplX1Qe0ivcFxYBmWHqZdi1IPHNNlhFNWTS5UjnVJ4/edit#gid=0

```[tasklist]
### Migrate the following builds to GitHub Actions
- [ ] https://github.com/guardian/frontend/issues/26045
- [ ] https://github.com/guardian/dotcom-rendering/issues/8647
- [ ] https://github.com/guardian/frontend-lambda/issues/47
- [ ] https://github.com/guardian/skimlinks-lambda/issues/8
- [ ] https://github.com/guardian/platform/issues/1547
- [ ] https://github.com/guardian/fastly-edge-cache/issues/1009
- [ ] https://github.com/guardian/dotcom-rendering/issues/8676
- [ ] https://github.com/guardian/fastly-image-service/issues/76
```

**Comment by ioannakok** [comment]
Closing as completed
