### ISSUE TITLE
Server render onwards content

### ISSUE THREAD

**Issue by oliverlloyd** [guardian/dotcom-rendering#5349]
### Onwards content

Articles and liveblogs have two rows of onwards content, e.g.
![image](https://user-images.githubusercontent.com/19683595/186442263-98a27d48-81f4-486c-9ef5-308e3559ed8f.png)

### Structure 
**Top row**  has one of the following in this priority order:
1. **More on this story**
![image](https://user-images.githubusercontent.com/19683595/186443212-8cf121a8-8196-4d67-a8aa-e8cdf74cac8d.png)

2. **Series**
![image](https://user-images.githubusercontent.com/19683595/186443754-d71ca0db-d63f-4a29-a19e-5e58c120901c.png)

3. **Popular in tag** (aka "Related content" - can easily get confused with "related stories" but it's _not_ the same)
![image](https://user-images.githubusercontent.com/19683595/186446772-7a86e0d1-79d4-4268-8e42-5b4e58375356.png)

4. **Related stories** 
![image](https://user-images.githubusercontent.com/19683595/186446282-677e01ec-2095-45c9-a974-a4f867a9a9dc.png)

**Bottom row**
**Curated content** (always) (e.g. More from Sport, Headlines, Culture etc.)
![image](https://user-images.githubusercontent.com/19683595/186444604-c82d194a-8af4-46ca-94de-f7cff1919cb5.png)

![image](https://user-images.githubusercontent.com/19683595/186445412-53958a61-4811-4f72-9583-202a0c7411f4.png)

## What is this epic about?
We want to server render _all_ onwards content (almost all - see below the section about `related-stories`) .

### Now
`more-on-this-story` - This is already server side rendered with the data provided by CAPI.
`popular-in-tag` - This is currently fetched as json by the client and rendered on the client.
`series` - This is currently fetched as json by the client and rendered on the client.
`related-stories` - This is currently fetched as json by the client and rendered on the client.
`curated-content` - This is currently fetched as json by the client and rendered on the client.

See here for client side logic: https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/components/OnwardsUpper.importable.tsx

### Target
`more-on-this-story` - No change
`popular-in-tag` - This will be read from a cache on Frontend, inserted into the DCR model and then server side rendered by DCR
`series` - This will be read from a cache on Frontend, inserted into the DCR model and then server side rendered by DCR
`related-stories` - This will still be fetched from the client but as html, not json. We cannot have an in memory cache for this because it is calculated per article basis by making a CAPI query. Fetching it from the client as html is enough to allow us unblock the `Picture` work. However, there is the option to add this information in the initial article json we're getting from frontend (see more in the ticket).
`curated-content` - This will be read from a cache on Frontend, inserted into the DCR model and then server side rendered by DCR

## Why do we want to do this?
We want to use the `Picture` component in `Card` (See: #4611 ) but that adds a constraint to how we render the `Card` component, it can only happen on the server. Currently we make an api call on the client and render the component there which causes errors when the `Picture` component is used.

## Basic flow for articles

```mermaid
graph TD
    A(S3) --> A1(facia) --> |Curated content agent| A7{Article Lifecycle} --> A2(Cache populated with curated content) --> A3(Onwards Picker) -->|Onwards content| A4(ArticleController) --> A5(DCR model) --> A6(DCR)
    B(CAPI) --> |Popular In Tag agent| A7 --> B2(Cache populated with popular in tag content) --> A3
    C(CAPI) -->|Series agent| A7 --> C1(Cache populated with series content) --> A3
    D(CAPI) --> D2(onwards app) -->|Related stories| A6
```

## Tickets
- [x] https://github.com/guardian/dotcom-rendering/issues/5734
- [ ] Curated content
  - https://github.com/guardian/dotcom-rendering/issues/5567
  - https://github.com/guardian/dotcom-rendering/issues/5842
- [ ] Popular In Tag
  - https://github.com/guardian/dotcom-rendering/issues/5568
  - https://github.com/guardian/dotcom-rendering/issues/5843
- [ ] Series
  - https://github.com/guardian/dotcom-rendering/issues/5569
  - https://github.com/guardian/dotcom-rendering/issues/5844
- [ ] Related content 
  - https://github.com/guardian/dotcom-rendering/issues/5570
- [ ] https://github.com/guardian/dotcom-rendering/issues/5566
- [ ] https://github.com/guardian/dotcom-rendering/issues/5942
- [ ] https://github.com/guardian/dotcom-rendering/issues/5943
- [ ] https://github.com/guardian/dotcom-rendering/issues/5846

### Options 
(We have decided to go with 1 but keeping this here for reference)
1) We could simply server render onwards content, this would remove the client side call and render.

2) Instead of calling an endpoint to fetch json data and rendering on the client we could fetch html data (which was rendered on the server) and insert that

**Comment by oliverlloyd** [comment]
Depends on #5472

**Comment by ioannakok** [comment]
Update:

Because it is difficult to test all the agents at once and in order to unblock the picture work, we're working on:

`popular-in-tag` - Fetched from the client as html.
`series` - Fetched from the client as html.
`related-stories` - Fetched from the client as html.
`curated-content` - This will be read from a cache on Frontend, inserted into the DCR model and then server side rendered by DCR: Draft PR with working agent: https://github.com/guardian/frontend/pull/25435

Once `picture` gets unblocked the plan is to do the agents work for `popular-in-tag` and `series`.

**Comment by ioannakok** [comment]
The team discussed on 14/9. The decision was, in order to unblock the picture work:
 
1. Wrap up the onwards work by adding html endpoints for `popular-in-tag`, `series` and `related-stories` + an agent for `curated-content`. There are currently draft PRs under review / being gradually merged:
* Curated content agent: https://github.com/guardian/frontend/pull/25435
* Popular In tag html endpoint: https://github.com/guardian/frontend/pull/25486
* Related content html endpoint: https://github.com/guardian/frontend/pull/25494
* Series html endpoint: https://github.com/guardian/frontend/pull/25504
* OnwardsPicker logic: https://github.com/guardian/frontend/pull/25467

The challenges in adding agents for all onwards are discussed in this RFC plus an alternative solution for the future: https://docs.google.com/document/d/1BIXhEoyZFIbMnxaF8ui2mLdgCBR6QJnrDQAUf8cuwto/edit#heading=h.ronehjbru84

2. In parallel, another piece of work on DCR images starts that can also unblock fronts and is a sensible thing to do anyway. See discussion here: https://docs.google.com/document/d/1MOUrtpTgSbFUEyCojrFbdgHyrpQ-88Mr4_wimOaM_zw/edit#heading=h.97lrr7pz4ag8

**Comment by ioannakok** [comment]
In order to reflect this decision on the wall, I'm parking / removing the following tickets from "Sprint focus" and Fronts blocking label.
* https://github.com/guardian/dotcom-rendering/issues/5568. Replaced  by: https://github.com/guardian/dotcom-rendering/issues/6020
* https://github.com/guardian/dotcom-rendering/issues/5570. Replaced by: https://github.com/guardian/dotcom-rendering/issues/6021
* https://github.com/guardian/dotcom-rendering/issues/5569. Replaced by: https://github.com/guardian/dotcom-rendering/issues/6022

**Comment by ioannakok** [comment]
Closing this epic and its tickets as in 22/9 planning meeting the team decided we are not implementing this solution. In order to unblock fronts we're going with [images without salts](https://github.com/guardian/dotcom-rendering/issues/6036) solution.
