### ISSUE TITLE
Deeply Read Experiment

### ISSUE THREAD

**Issue by mxdvl** [guardian/dotcom-rendering#5554]
# Deeply Read Experiment

We want to run an experiment where users would be shown some of the most deeply read articles on the Guardian, sorted by edition.

## Where do we want to run this experiment?
- [ ] Network fronts
- [ ] Tag fronts?
- [ ] Articles?

## Creating the Agents
The agents need to handle all editions.

- [x] https://github.com/guardian/dotcom-rendering/issues/5664
- [x] https://github.com/guardian/dotcom-rendering/issues/5662
- [x] https://github.com/guardian/dotcom-rendering/issues/5660
- [ ] https://github.com/guardian/frontend/pull/25358

## Setting the test
- [ ] Create a server-side test for 5% of users
- [ ] Measure impact with D&I

## Drive-by Improvements
- [ ] Server-render “Most Viewed” on DCR
- [ ] Server-render “Across the Guardian” on Frontend + DCR

## What data is powering what?

![onwards-mostpopular](https://user-images.githubusercontent.com/31692/184098480-efa7383b-e9d7-4541-982c-9bdee38fb5ec.png)

---

## Previous 🎨 

- [Deeply Read test doc - June 2022](https://docs.google.com/document/d/1dutAGHapw7Y-jZc6jMv_64OdDLxm6tu6SZVuF989CHc/edit)

- ['Deeply Read' API endpoint in Ophan](https://docs.google.com/document/d/1FSfB47-bZ2CFvbATzDqFst6j-6JNCkgsSPKQKFnQRhU/edit)

Original implementation & test in late 2020 / early 2021

- https://github.com/guardian/frontend/pull/23364
- https://github.com/guardian/frontend/pull/23365
- https://github.com/guardian/frontend/pull/23366
- https://github.com/guardian/frontend/pull/23367
- https://github.com/guardian/frontend/pull/23368
- https://github.com/guardian/frontend/pull/23369
- https://github.com/guardian/frontend/pull/23254
- https://github.com/guardian/frontend/pull/23376
- https://github.com/guardian/frontend/pull/23377
- https://github.com/guardian/frontend/pull/23379

- https://github.com/guardian/frontend/pull/23665

**Comment by mxdvl** [comment]
See test cleanup PR [frontend#23665](https://github.com/guardian/frontend/pull/23665)

**Comment by VDuczekW** [comment]
Web X will not work on this - the ticket link has been passed on to EDX
