### ISSUE TITLE
[EPIC] Review container controls supported by Frontend but not DCR

### ISSUE THREAD

**Issue by AshCorr** [guardian/dotcom-rendering#6392]
During a recent demo of the the Fronts tool we noticed that a few of the controls for showing standfirst, showing kickers, etc were not working on the DCR version of a front.

This issue should be used for tracking which controls we support.

## Card Controls

![image](https://user-images.githubusercontent.com/21217225/200361690-e3f1beb2-7e58-4ab2-bd51-70052992e721.png)

- [x] Kicker
- [x] Headline
- [x] Boost - https://github.com/guardian/dotcom-rendering/issues/4948 | APP notes: not applicable to dynamic/fast in the app but does work on tablet 
- [x] Large headline - Not being used, does not need support, CP will discuss removing with digi eds
- [x] Quote headline - Now supported #6443 - does not have an effect on sublinks on web (we should fix this)
- [x] Breaking News - Now supported #6444
- [x] Show Byline
- [x] Trail text
- [x] Hide media
- [ ] Use cutout - We need to support use cutout when a byline image exists in tag manager large byline - https://github.com/guardian/dotcom-rendering/issues/8006
- [ ] #6662 - **Not required for 1%** - does not work on the app
- [x] Slideshow - https://github.com/guardian/dotcom-rendering/issues/5654 
- [x] #6661

## Front Metadata Controls

![image](https://user-images.githubusercontent.com/21217225/200365545-67947c72-3b70-421a-8876-c0074d69e9c9.png)

- [x] Hidden
- [x] Nav section
- [x] Name
- [x] SEO title
- [x] #6657
- [x] #6658
- [x] Image - Not supported. Only 1 front uses this and has "Display image" enabled and the first container on that front is a thrasher so it doesn't get displayed anyway. - CP will discuss removing with digi eds
- [x] Display image - Controls if the aforementioned image is show. - CP will discuss removing with digi eds

## Edit Container

![image](https://user-images.githubusercontent.com/21217225/200366115-ad58efea-fe4b-469a-a7eb-514f72c162a5.png)

- [x] Title
- [x] Link url - Not supported #6430
- [x] Description - Not supported #6433 
- [x] Backfill
- [x] Tags
- [x] User visiblity - **Does not seem to affect either platform**
- [x] #6646
- [x] Show tag kickers
- [x] Show section kickers
- [x] Supress tone kickers - we don't think it's used, will not support in DCR - CP will discuss removing with digi eds
- [x] Show date in header - not sure if supported on APP
- [x] Show latest update in header - Not being used, does not need support, CP will discuss removing with digi eds https://github.com/guardian/dotcom-rendering/issues/6437
- [x] Hide show more - Supported once #6262 is merged and [comment](https://github.com/guardian/dotcom-rendering/pull/6262/files#r1020357179) is resolved
- [x] Platform

**Comment by paperboyo** [comment]
> * Use cutout - Not supported, looks awful in Frontend though, maybe I'm using it wrong, to confirm what its for with CP.

This controls when to use Large byline for author’r cutout (frontstool switches it ON by default on Comment cards, where the cutout exists). It should work on all card types. When we redesigned Garnett, some cards were not migrated to use the new style of cutouts presented in circles. Pending Harry’s ruling, they probs should (or – already have).

Regardless, we used to have an option to supply the cutout **manually** via frontstool (“Replacement cutiyt” where you add a URL to a pic in frontstool). While this is still an option in frontstool (it should be removed), by Editorial decision, this functionality should be removed (no need for any platforms to support those cutouts). Nobody was using it anyway since around the end of the Vietnam war. Or something.

**Comment by rhiannareechaye** [comment]
Let's do this as a group together so that we can gain an understanding of whether or not these are 'Musts' @alinaboghiu will put a meeting in

**Comment by alinaboghiu** [comment]
We should have stories for each of these variations in storybook

**Comment by DavidLawes** [comment]
Just for reference, here are the config options supported on the app:

**Card config:**

- kicker - supported
- headline - supported
-boost - some support (layout can override any choices made in fronts tool)
- large headline - not supported / used
- quote headline - supported (article + sublink)
- breaking news kicker - supported
- show byline - supported
- trail text - supported (unless deliberately hidden e.g. video cards)
- hide media - supported (inc. display cards)
- use cutout - supported
- show video - not supported (for now, can't play videos directly on a front atm)
- slideshow - supported
- replace image - supported


**Container metadata:**

- hidden - supported
- nav section - not supported
- name - supported
- seo title - not supported/applicable
- meta description - not supported/applicable
- on-page description - not supported (for now)
- image - not supported
- display image - not supported


**Container config:**

- title - supported
-link url - supported
- description - not supported (for now)
- backfill - supported
- tags - supported
- user visibility - supported
- geo-targeted containers - supported
- tag kickers - supported
- section kickers - supported
- suppress tone kickers - not supported
- show date in header - not supported (for now)
- show latest update in header - not supported
- hide show more - not supported
- platform - supported
