### ISSUE TITLE
Remove trailing slashes from card headlines

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#6943]
[Figma designs](https://www.figma.com/file/WvHeA8hXpqDweotAuKasMn/No-more-slashes-on-cards?node-id=0%3A1&t=2Zonp4nHWB0HcA1O-0) for this change.

## 0% Test

- [x] #7014
- [x] Frontend
    - [x] regular cards (`.fc--item__kicker`) -- [Frontend #25845](https://github.com/guardian/frontend/pull/25845)
    - [x] #7015
    - [x] `flagshipContainer` ('Today in Focus') -- [Frontend #25861](https://github.com/guardian/frontend/pull/25861) 
    - [x] most viewed 
        - nb. edits to the `@title` component and `.fc--items__kicker` should affect this component the same way it does for regular cards.
    - [x] #7077
- [x] DCR
    - [x] #7032
    - [x] #7050
- [x]  Other
    - [x] [commercial-templates](https://github.com/guardian/commercial-templates/pull/325)

## Release

- [x] #7051 
- [x] [Frontend #25862](https://github.com/guardian/frontend/pull/25862)
- [x] [Move the 'external link' icon on Frontend](https://github.com/guardian/frontend/pull/25870)
