### ISSUE TITLE
[Sub-epic] Fronts design review bugs 2023/02/20

### ISSUE THREAD

**Issue by bryophyta** [guardian/dotcom-rendering#7287]
There is [a primary epic](https://github.com/guardian/dotcom-rendering/issues/6644) for this, which contains earlier bugs which are mostly fixed at this point.

## Bugs from the February 20th review (high priority)

- [x] [FaciaPicker isn't checking for snapLink cards](https://github.com/guardian/frontend/issues/25922)
- [ ] FastVIII -- missing vertical dividers
- [ ] Show more button API URL is using wrong id
- [ ] Remove special headline colours for Feature cards
- [ ] Kicker colours bugs
- [ ] Align treats to bottom of the container
- [ ] Dynamic slow MPU space filling bug
- [ ] Unstyled text in 'description' on crosswords container
- [ ] Topics text is unstyled
- [ ] Media card background colour should match Frontend
- [ ] `Highlights of the day` first card not boosting correctly?
- [ ] Cartoon cards are incorrectly showing quote marks
- [ ] Byline on cards is sometimes pulling in reporter's role
