### ISSUE TITLE
Sub-Meta Design Change

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#7389]
Changes to the way tags at the bottom of articles are laid out.

```[tasklist]
### Tasks
- [x] Create Designs
- [ ] https://github.com/guardian/dotcom-rendering/issues/8768
- [ ] https://github.com/guardian/dotcom-rendering/issues/8792
- [ ] https://github.com/guardian/dotcom-rendering/issues/8769
- [ ] https://github.com/guardian/dotcom-rendering/issues/8770
- [ ] https://github.com/guardian/dotcom-rendering/issues/8771
- [ ] https://github.com/guardian/dotcom-rendering/issues/8793
```

## Apps
https://mobile.guardianapis.com/rendered-items/politics/2023/may/09/liz-truss-to-visit-taiwan-and-give-speech-that-could-upset-uks-china-strategy

<img width="636" alt="Screenshot 2023-07-25 at 17 29 29" src="https://github.com/guardian/dotcom-rendering/assets/31692/9abc94f3-189b-46e5-8489-27e9cf295a96">

## DCR
https://www.theguardian.com/politics/2023/may/09/liz-truss-to-visit-taiwan-and-give-speech-that-could-upset-uks-china-strategy?dcr=apps

<img width="707" alt="Screenshot 2023-07-25 at 17 13 37" src="https://github.com/guardian/dotcom-rendering/assets/31692/59d5f4cc-fc6e-4153-a0df-bd775a8425cf">

@ajbreuer to provide designs for this.
https://docs.google.com/document/d/1UaNHA1gHlvmXxzY5-UgXfx-w4mFrJI-x5ljk54OGyYk/edit#heading=h.lbz9nzm7oeta

**Comment by rhiannareechaye** [comment]
We'll aim to get the design work completed by the 5th of June

**Comment by rhiannareechaye** [comment]
https://www.figma.com/file/R5kfAuzgovB4lVlCKKyCww/DCAR-Anomalies-and-App-preferences?type=design&node-id=1-2&mode=design&t=C5aHQBDRU4szVXrV-0

**Comment by ajbreuer** [comment]
![Image](https://github.com/guardian/dotcom-rendering/assets/1144827/b8d38c0c-ff9e-43dc-a9fb-ea165acb71aa)

This is the new design. You will see this in this figma doc
https://www.figma.com/file/R5kfAuzgovB4lVlCKKyCww/DCAR-Anomalies-and-App-preferences?type=design&node-id=1%3A2&mode=design&t=2w0czeoHzjliziOU-1

**Comment by abeddow91** [comment]
@ajbreuer Tags also sit at the bottom of fronts (screenshot below). Would we expect the same styling changes here? if so, what colour should these pick up?

![Image](https://github.com/guardian/dotcom-rendering/assets/20416599/cb61fe4f-89a0-474e-8978-ee1651d76bcf)

**Comment by abeddow91** [comment]
There is a PR here that covers the article changes. Additional work will be required to update these on fronts

**Comment by abeddow91** [comment]
blocked whilst we wait for a decision on if this needs to be implemented on all platforms (ar, apps templates dcar) or dcar

**Comment by paperboyo** [comment]
All tasks done, maybe this was completed?
