### ISSUE TITLE
[EPIC] DAC tickets

### ISSUE THREAD

**Issue by rhiannareechaye** [guardian/dotcom-rendering#7652]
```[tasklist]
## Things we still need to support on snaps and thrashers
- [ ] https://github.com/guardian/dotcom-rendering/issues/5075
- [ ] https://github.com/guardian/dotcom-rendering/issues/4455
- [ ] https://github.com/guardian/dotcom-rendering/issues/4456
- [ ] https://github.com/guardian/dotcom-rendering/issues/5082
- [ ] https://github.com/guardian/dotcom-rendering/issues/4496
- [ ] https://github.com/guardian/dotcom-rendering/issues/5051
- [ ] https://github.com/guardian/dotcom-rendering/issues/4446
- [ ] https://github.com/guardian/dotcom-rendering/issues/5066
- [ ] https://github.com/guardian/dotcom-rendering/issues/5069
- [ ] https://github.com/guardian/dotcom-rendering/issues/5071
- [ ] https://github.com/guardian/dotcom-rendering/issues/5072
- [ ] https://github.com/guardian/dotcom-rendering/issues/5074
- [ ] https://github.com/guardian/dotcom-rendering/issues/5076
- [ ] https://github.com/guardian/dotcom-rendering/issues/5078
- [ ] https://github.com/guardian/dotcom-rendering/issues/5080
- [ ] https://github.com/guardian/dotcom-rendering/issues/5081
- [ ] https://github.com/guardian/dotcom-rendering/issues/5083
- [ ] https://github.com/guardian/dotcom-rendering/issues/5335
- [ ] https://github.com/guardian/frontend/issues/25069
- [ ] https://github.com/orgs/guardian/projects/8/views/28?pane=issue&itemId=7054283
```
