### ISSUE TITLE
Ad parity

### ISSUE THREAD

**Issue by arelra** [guardian/dotcom-rendering#8082]
We should track ad parity for DCR vs Frontend network fronts.

D&I are working on creating an ad parity tracker.

We should agree the roll out % and schedule with D&I and Commercial dev

```[tasklist]
### Tasks
- [x] D&I to refresh ad parity tracker
- [x] mobile-6 ad slot is missing on the international front
- [x] merchandising-high and mobile1 slots differ in position compared to Frontend
- [x] mobile and desktop slots should be removed from the dom when not at that breakpoint
```

**Comment by arelra** [comment]
mobile6-inline is fixed by: https://github.com/guardian/dotcom-rendering/pull/8112

**Comment by rhiannareechaye** [comment]
https://docs.google.com/spreadsheets/d/1SKBBciRIWuxfXmTjGx0_CwbQktU5C2BP8h-hzHgmFIQ/edit#gid=1391693339

**Comment by rhiannareechaye** [comment]
Can we take a look at this too please: 

one quick one - I noticed the cycling had an ad slot missing on DCR on first slice of first container https://www.theguardian.com/sport/cycling?dcr=false vs https://www.theguardian.com/sport/cycling?dcr=true

**Comment by arelra** [comment]
> cycling had an ad slot missing on DCR

This is a tagged front for which ad slot support has just been merged with: https://github.com/guardian/dotcom-rendering/pull/8056

We should be seeing ad slots on tagged fronts appear soon
