### ISSUE TITLE
[EPIC] Tag Fronts

### ISSUE THREAD

**Issue by OllysCoding** [guardian/dotcom-rendering#8314]
### What are tag fronts?

Fronts can generally be separated into two categories: 

1. **Pressed Fronts** - These fronts, like https://www.theguardian.com/uk are ones that are created in the fronts tool by digital editors, and are then 'pressed' into a JSON form by `facia-press` in Frontend.
2. **Tag Fronts** - These fronts are created automatically, and come with a tag created in tag manager. They display a date ordered set of content associated with a given tag.

DCR's pressed front rollout is (almost) complete - but tag fronts need their own data model & features, which need to be built & supported.

## What's left to do?

```[tasklist]
### Pre 1%
- [ ] Address ordering bug (ensure grouped cards are sorted)
- [ ] Tidy up spacing on pagination
- [ ] Fix font sizing / color on containers
- [ ] Investigate ‘missing’ days (e.g most recent days content missing on tone/minutebyminute
- [ ] Create & launch 1% test
```

```[tasklist]
### Post 1%
- [ ] Support individual date routes (/all)
- [ ] Support /theguardian and theobserver
- [ ] Support tag combiners
```

```[tasklist]
### Subjects / Contributors
- [ ] Support subjects pages
- [ ] Support contributor pages
```

**Comment by OllysCoding** [comment]
### Revisiting Tag Fronts? Here's what you need to know

**What are they?**
Tag fronts are automatically generated fronts that exist alongside a tag created in tag manager. They are paginated pages which display all the content published to a tag in date order.

Stories on tag fronts are grouped into containers much like on pressed fronts, however since there's no curation, containers are date based, a container will either show all the stories for a given day, or a given month, depending on the frequency content is being published to that tag.

The standard URL for a tag front is `www.theguardian.com/<tag  id>`. Tags IDs generally contain a forward slash `/`, e.g `tone/minutebyminute`. When either side of the tag is the same, e.g `politics/politics`, the url would only contain the one part, e.g `www.theguardian.com/politics`.

Tag fronts can be _overwritten_ by pressed fronts, e.g in the case of https://www.theguardian.com/tone/recipes. In this case, the tag front can be found at `www.theguardian.com/<tag ID>/all`, e.g https://www.theguardian.com/tone/recipes/all.

TODO

- What urls are currently supported
- what functionality is supported
- How to pick up dev work
