### ISSUE TITLE
Review DCR's ASG Configuration

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#8345]
Now that we're serving fronts traffic it might be a good time to review, to establish whether we're:

1. Using the best instance types for our use-case
2. Scaled to an appropriate count, with adequate min and max counts that allow for RiffRaff deploys
3. Applying the best scaling policy for our needs

Suggestions derived from conversations with @alinaboghiu and @jacobwinch .

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/9322
- [ ] https://github.com/guardian/dotcom-rendering/issues/9311
- [ ] https://github.com/guardian/dotcom-rendering/issues/9321
- [ ] https://github.com/guardian/dotcom-rendering/issues/9310
- [ ] https://github.com/guardian/dotcom-rendering/issues/9963
- [x] Once https://github.com/guardian/dotcom-rendering/issues/8351 is complete - revisit each new stack ASG size and instance types
```

## Instance Types

We're currently using `t4g.small` in production:

https://github.com/guardian/dotcom-rendering/blob/e234547e28cb1071b83c526fdbae7df5c361f522/dotcom-rendering/scripts/deploy/riff-raff.yaml#L16-L19

Do we want to consider other instance types? Frontend uses a different type, as mentioned in #7440.

## ASG Size

We're currently using a minimum of 15 and a maximum of 60 instances in production:

https://github.com/guardian/dotcom-rendering/blob/e234547e28cb1071b83c526fdbae7df5c361f522/dotcom-rendering/cloudformation.yml#L72-L78

Do these limits allow enough headroom for our additional traffic, scaling requirements, and RiffRaff deploys?

## Scaling Policy

We're currently scaling based on latency:

https://github.com/guardian/dotcom-rendering/blob/e234547e28cb1071b83c526fdbae7df5c361f522/dotcom-rendering/cloudformation.yml#L312-L331

and scaling up by doubling our capacity every 10 minutes:

https://github.com/guardian/dotcom-rendering/blob/e234547e28cb1071b83c526fdbae7df5c361f522/dotcom-rendering/cloudformation.yml#L304-L310

whilst scaling down by removing an instance once every 2 minutes:

https://github.com/guardian/dotcom-rendering/blob/e234547e28cb1071b83c526fdbae7df5c361f522/dotcom-rendering/cloudformation.yml#L296-L302

Do we want to consider other scaling strategies? Apps-rendering, for example, via `guardian/cdk`, scales based on a target CPU utilisation:

https://github.com/guardian/dotcom-rendering/blob/e234547e28cb1071b83c526fdbae7df5c361f522/apps-rendering/cdk/lib/mobile-apps-rendering.ts#L104-L106

@akash1810 recommends to have a completed test before Christmas holidays and base on that we decide what to do.

**Comment by jamesgorrie** [comment]
Something I think that is also worth adding to this discussion is how we might have scaling work in lockstep with `frontend`.

Out current setup of code, not-colocated, makes it seem as though there is no coupling between this AWS configuration, and frontend's AWS configuration. 

I'd suggest there is strong coupling. If we scale up the `frontend/facia` app, we will send more traffic to `dcr`. We should account for this as failing at the `dcr` level will cause just as many issue, especially given its current "I serve HTML for all the things" setup.

We should probably consider that we are planning on being able to scale up separately across endpoints in `dcr` soon too to avoid that single point of failure.

**Comment by jacobwinch** [comment]
Thanks for writing this up @JamieB-gu!
 
> 3. Applying the best scaling policy for our needs

IIUC this app ([and other Dotcom apps](https://github.com/guardian/platform/blob/760a56925f7da301a6f91e0eb1e54b6a9abb0190/provisioning/cloudformation/frontend-service.yaml#L498-L512)) are currently using simple scaling[^1]. AWS have [essentially deprecated this style of scaling](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-scaling-cooldowns.html) and are promoting their alternative solutions as a best practice:

![image](https://github.com/guardian/dotcom-rendering/assets/19384074/d6dc8d53-c186-48c1-9fe4-693233dc887c)

I would recommend experimenting with these alternative strategies (regardless of which metric you decide to base your scaling on) if you have some time.

[^1]: It's a bit tricky to see this, but [simple scaling is the default](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-autoscaling-scalingpolicy.html#cfn-autoscaling-scalingpolicy-policytype), so if `PolicyType` is unspecified, you're using `SimpleScaling`.

**Comment by AshCorr** [comment]
Worth noting that even though we're paying for a `t4g.small` instances with 2 vCPUs in PROD I'm not convinced we actually use the 2nd CPU for DCR. I don't think we have PM2 configured correctly for clustering to take advantage of the 2nd vCPU.

**Comment by arelra** [comment]
> Worth noting that even though we're paying for a `t4g.small` instances with 2 vCPUs in PROD I'm not convinced we actually use the 2nd CPU for DCR. Due to Nodes single threaded nature it will only use one of the CPUs, usually something like PM2 would create multiple node instances for each CPU to fix that but I don't think we've configured it to do that in our case.

@AshCorr Snap. I'm looking at configuring clustering

**Comment by jamesgorrie** [comment]
> We should probably consider that we are planning on being able to scale up separately across endpoints in `dcr` soon too to avoid that single point of failure.

Talking to myself - there is [an issue](#8351) that speaks to this and might be considered in conjunction with this as we can think of scaling as domain and traffic specific to those parts of the site.

**Comment by rhiannareechaye** [comment]
hey @jamesgorrie I've moved this into the triage column - what do you think the next step is for this piece of work. Do you think it should be prioritised as a 'high impact' ?

**Comment by rhiannareechaye** [comment]
Moving to the backlog - please note this isn't in our list for planning for the near future, please shout if you disagree though (and feel free to add to the list to be discussed in planning: https://docs.google.com/document/d/1-ls95KamOB-lvwKzTUfqpd3gSwcvgszC7fsMIOhXacM/edit)

**Comment by rhiannareechaye** [comment]
We'll be prioritising PM2/Vulnerabilities at the moment, and working out a way to surface this on a backlog (we'll try and trial a new approach to health for the new Q)

**Comment by ioannakok** [comment]
Progress so far: https://docs.google.com/document/d/1FjDANYnddGrB3JnXdMjoHnie2kB7fL3MgJachCVZHVg/edit
