### ISSUE TITLE
[Epic]: DCR for Apps - Bridget Commercial Service (Native Ads)

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#8592]
We will be replicating the current way of doing apps in `app-rendering`.

This is creating open slots in DCR and publicising their location to the native layer which will inject ads there.

We should be working closely with @guardian/commercial-dev on this as they have ambitions to use web rendering for ads.

The reason not to move directly to web ads is:
- We might hit blockers e.g. consent, ad tech, etc, which we don't want to block the whole project on
- It would be good to have the old system to test against any new system

This is more than likely a more complex integration with [Bridget](https://github.com/guardian/bridget) than others.

Depending on the outcome of #8381 we may want to add support for native ads, which are powered by the Bridget `Commercial` service. Before embarking on this, talk to the Commercial team to see where they've got to investigating #8381.

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/8752
- [ ] https://github.com/guardian/dotcom-rendering/issues/8812
- [ ] https://github.com/guardian/dotcom-rendering/issues/8823
- [ ] https://github.com/guardian/dotcom-rendering/issues/8835
- [ ] https://github.com/guardian/dotcom-rendering/issues/8804
- [ ] https://github.com/guardian/dotcom-rendering/issues/8822
- [ ] https://github.com/guardian/dotcom-rendering/issues/8878
- [ ] https://github.com/guardian/dotcom-rendering/issues/8887
- [ ] https://github.com/guardian/dotcom-rendering/issues/8888
- [ ] https://github.com/guardian/dotcom-rendering/issues/8903
- [ ] https://github.com/guardian/dotcom-rendering/issues/7393
- [ ] https://github.com/guardian/dotcom-rendering/issues/9039
```

**Comment by JamieB-gu** [comment]
#9039
