### ISSUE TITLE
[Epic]: DCR for Apps - Layouts

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#8742]
We need to support all Article Layouts in [`DecideLayoutApps`](https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/layouts/DecideLayout.tsx#L30-L65).

[There is an example PR for `StandardLayout` here](https://github.com/guardian/dotcom-rendering/pull/7677).

We will need to work our way through [these layouts](https://github.com/guardian/dotcom-rendering/tree/main/dotcom-rendering/src/layouts).

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/8786
- [ ] https://github.com/guardian/dotcom-rendering/issues/8995
- [ ] https://github.com/guardian/dotcom-rendering/issues/8998
- [ ] https://github.com/guardian/dotcom-rendering/issues/8999
- [ ] https://github.com/guardian/dotcom-rendering/issues/8997
- [ ] https://github.com/guardian/dotcom-rendering/issues/9000
```

## These should just work

- Standard
- Review
- Analysis
- Explainer
- Comment
- Letter
- Feature
- Recipe
- Interview
- Editorial
- Quiz
- PhotoEssay
- PrintShop
- Obituary
- Correction
- Timeline
- Profile

## These might need to effort / testing to get working

- LiveBlog
- DeadBlog
- MatchReport
- Interactive
- FullPageInteractive
- NewsletterSignup

## Not Supported By DCR

- Picture
- Gallery
- Audio
- Video

**Comment by JamieB-gu** [comment]
The remaining tasks are tracked separately, so we no longer need this issue.
