### ISSUE TITLE
[Epic]: DCR for Apps - Liveblogs

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#8743]
We think this should just be working due to the hydration work that has been done.

It feels prudent to test:
- [ ] Pagination
- [ ] Permalinks to specific blocks
- [ ] How this works offline
- [ ] How video would work (this might be part of #8741)
