### ISSUE TITLE
[Epic]: DCR for Apps - Discussion

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#8745]
## Overview

This quarter (Jan-Mar 2024) we’ll be working on implementing discussions in DCAR. We hope will reduce the amount of platform-specific logic in favour of a unified approach. We may also use this as an opportunity to simpliying existing the code and fix bugs.

## Key changes required

Discussion in web and Apps differs in that in Apps post endpoints interact with the native layer directly as that's where the user information is know. e.g. `postComment` or `reportAbuse`

There has been some work to account for this by [using callbacks on the `CommentContainer`](https://github.com/guardian/dotcom-rendering/blob/2926f9836accef42a9130b7fb61ba7ba2966280b/dotcom-rendering/src/components/Discussion/CommentContainer.tsx#L29-L37).

When migrating [`discussion-rendering`](https://github.com/guardian/discussion-rendering) we had opted for expediency to not always follow this pattern, so will need to find those interactions that speak to the discussion API directly and port them over to the paradigm above.

We might need to work with Apps here to help create any endpoints that don't exist.

```[tasklist]
### Step 1 - Beta release
- [ ] #9667
- [ ] #10056
- [ ] #10071
- [ ] https://github.com/guardian/dotcom-rendering/issues/10565
- [ ] #10417
```

```[tasklist]
### Step 2 - Beta or PROD release
- [ ] #10548
- [ ] #9869
- [ ] #10331
- [ ] https://github.com/guardian/dotcom-rendering/issues/10735
- [ ] #10288
- [ ] #10551
- [ ] #10549
- [x] Mute functionality on device
```

```[tasklist]
### Step 3 - PROD release
- [ ] https://github.com/guardian/dotcom-rendering/issues/10734
```

```[tasklist]
### Unprioritised / other
- [ ] #10416
```

**Comment by alinaboghiu** [comment]
Duplicated

**Comment by mxdvl** [comment]
Rough tasks that need addressing

- How does sign-in works with Bridget?
- How do fetch requests work in WebViews?
- How is saving preferences handled?
- How should discussion behave when offline?
