### ISSUE TITLE
[Epic]: DCR for Apps - release plan

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#8750]
We should be aiming to get some articles rendered via DCR into the PROD release of the app as soon as possible.

While we can, and should, rely on the Beta release, we should follow the current paradigm of how it is currently used:
```mermaid
flowchart LR
    subgraph Not This
        direction LR
        AddIncrementalSupportV2["Add incremental support"]-->TestInBetaV2["Test in Beta"]-->EveryThingDone{"Is it all done?"}-->|No|AddIncrementalSupportV2
        EveryThingDone{"Is it all done?"}-->|Yes|ReleaseToProdV2["Release to prod"]
    end
    subgraph This
        direction LR
        AddIncrementalSupport["Add incremental support"]-->TestInBeta["Test in Beta"]-->ReleaseToProd["Release to Prod"]-->AddIncrementalSupport
    end
```

We will release the project in 3 phases:
- Release to Beta users
- Release to Prod users
- Release to Prod based on content (CAPI) structure

```[tasklist]
### Beta release
- [ ] #8747
- [ ] #7301
- [ ] https://github.com/guardian/mobile-apps-api/pull/2711
- [ ] Bridget integrations
```

```[tasklist]
### Initial Prod release
- [ ] #8729 
- [ ] https://github.com/guardian/dotcom-rendering/issues/9130
- [ ] https://github.com/guardian/dotcom-rendering/issues/7301
- [ ] https://github.com/guardian/dotcom-rendering/issues/8747
```

```[tasklist]
### Incremental prod release
- [ ] #8745 
- [ ] #8742 
- [ ] #8741 
``` 

To incrementally release to readers we'll need to start updating [`DcrSupportUtils` in MAPI](https://github.com/guardian/mobile-apps-api/blob/ccdc6d0e405d4ca393917f560f080ca05677bbb7/common-play/src/main/scala/data/DcrSupportUtils.scala#L16).

As part of this we must expand our logging to help us identify areas we could focus on to increase coverage for DCR.

**Comment by michaelclapham** [comment]
Are bridget integrations for making sure adverts show up needed for beta?

**Comment by JamieB-gu** [comment]
The remaining tasks are tracked separately, so we no longer need this issue.
