### ISSUE TITLE
[Epic]: DCR for Apps - 🚀 Beta release

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#8815]
```[tasklist]
### Tasks
- [ ] #8964
- [ ] https://github.com/guardian/dotcom-rendering/issues/9116
- [ ] https://github.com/guardian/dotcom-rendering/issues/8992
- [ ] https://github.com/guardian/dotcom-rendering/issues/9085
- [ ] https://github.com/guardian/dotcom-rendering/issues/9245
- [ ] https://github.com/guardian/dotcom-rendering/issues/8993
```
