### ISSUE TITLE
[Epic]: DCR for Apps - 🚀 Production release

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#8816]
This is a list of tasks required to get **some** articles rendering in production. Further work required to complete the rollout and get **all** articles rendering in production is tracked in #8817.

```[tasklist]
### First production release
- [ ] https://github.com/guardian/dotcom-rendering/issues/9130
- [ ] https://github.com/guardian/dotcom-rendering/issues/7390
- [ ] https://github.com/guardian/dotcom-rendering/issues/9289
- [ ] https://github.com/guardian/dotcom-rendering/issues/9762
- [ ] https://github.com/guardian/dotcom-rendering/issues/9110
- [ ] https://github.com/guardian/dotcom-rendering/issues/7301
- [ ] https://github.com/guardian/dotcom-rendering/issues/7072
- [ ] https://github.com/guardian/dotcom-rendering/issues/9220
- [ ] https://github.com/guardian/dotcom-rendering/issues/9480
- [ ] https://github.com/guardian/dotcom-rendering/issues/12604
- [x] Update `DCRSupportUtils` In MAPI To Release To Production
```

**Comment by JamieB-gu** [comment]
The remaining tasks are tracked separately, so we no longer need this issue.
