### ISSUE TITLE
[Epic]: DCR for Apps - 🚀 Post production release

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/dotcom-rendering#8817]
The list of tasks required to get **some** articles rendering in production is tracked in #8816. Subsequent work required to complete the rollout and get **all** articles rendering in production is tracked here.

```[tasklist]
- [ ] https://github.com/guardian/dotcom-rendering/issues/8747
- [ ] https://github.com/guardian/dotcom-rendering/issues/9241
- [ ] https://github.com/guardian/dotcom-rendering/issues/8729
```

**Comment by JamieB-gu** [comment]
The remaining tasks are tracked separately, so we no longer need this issue.
