### ISSUE TITLE
Okta: handle errors from `@guardian/identity-auth` 

### ISSUE THREAD

**Issue by georgeblahblah** [guardian/dotcom-rendering#8820]
We should handle these errors as we know they can and will happen for some users. At the moment, they are reaching Sentry. This means other errors are harder to see. We should do this in DCR, `@guardian/commercial` and `frontend`.

Thanks @SiAdcock for pointing it out!

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/commercial/pull/1087
- [ ] https://github.com/guardian/commercial/pull/1082
- [x] Update Commercial in Frontend
- [ ] https://github.com/guardian/dotcom-rendering/pull/9025
```

**Comment by rhiannareechaye** [comment]
Could this be a pick me up - or potentially handled when we look at the cypress tests for okta @georgeblahblah ?

**Comment by georgeblahblah** [comment]
From what I can tell, we already catch errors coming from Okta:

https://github.com/guardian/dotcom-rendering/blob/7fe3c9adf5cddc28830d433421a69085a2415fb2/dotcom-rendering/src/lib/useAuthStatus.ts#L88-L102

**Comment by georgeblahblah** [comment]
Not really blocked, just waiting on https://github.com/guardian/commercial/pull/1082 to be merged / a new version of `@guardian/commercial` to be released
