### ISSUE TITLE
DCR for apps - Handle consent natively

### ISSUE THREAD

**Issue by sophie-macmillan** [guardian/dotcom-rendering#8911]
We need to handle consents in DCR for apps

```[tasklist]
### Tasks
- [x] Ensure we are assuming reject all and understand how this affects ad placeholders
- [x] Align vendor list between apps and web (https://github.com/guardian/dotcom-rendering/issues/8747)
- [x] Hide web consent banner in articles in the app (https://github.com/guardian/dotcom-rendering/issues/8875)
- [x] Pull consent from the native layer into the webview
```

**Comment by falloutfox** [comment]
https://docs.google.com/document/d/17e35gkhBoM4SM-g-K90e1xj29MaYSYJMxF2Kpjw0Ktg/edit?usp=sharing

**Comment by mxdvl** [comment]
DCAR has had successful ads for a while, closing as completed – any remaining issue would be considered a bug.
