### ISSUE TITLE
[Epic]: Euros 2024

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#9040]
This runs from 14/06/2024 - 10/07/2024.

Some previous documenation: https://docs.google.com/document/d/1pmUYYfmJMYdjVodVYyCqBWxUOtVAQr6g5COWfYS-Fsw/edit#heading=h.tjte5ef1oh2f

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/11237
- [ ] https://github.com/guardian/dotcom-rendering/issues/7435
- [ ] https://github.com/guardian/dotcom-rendering/issues/7437
- [ ] https://github.com/guardian/dotcom-rendering/issues/7436
- [ ] https://github.com/guardian/dotcom-rendering/issues/7438
- [ ] https://github.com/guardian/dotcom-rendering/issues/11567
- [ ] https://github.com/guardian/dotcom-rendering/issues/11546
- [ ] https://github.com/guardian/dotcom-rendering/issues/7439
- [ ] https://github.com/guardian/dotcom-rendering/issues/11547
- [ ] https://github.com/guardian/dotcom-rendering/issues/11553
- [x] Update fixtures page with the right competition name
- [x] Update the Competitions with name "Euro 2024" instead of "Euro 2024 qualifying"
- [ ] https://github.com/guardian/dotcom-rendering/issues/11587
- [ ] https://github.com/guardian/dotcom-rendering/issues/11610
```

**Comment by mxdvl** [comment]
⚽ 🥅
