### ISSUE TITLE
Make All Newsletters Page Configurable By Editorial

### ISSUE THREAD

**Issue by cemms1** [guardian/dotcom-rendering#9044]
The newsletters grouping on the [all newsletters page](https://www.theguardian.com/email-newsletters) is currently manual. See https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/model/newsletter-grouping.ts

Since we anticipate the editorial newsletters team will want to amend this regularly, we should think about how to move management of this page into an internal tool (possibly the frontend tool or the newsletters tool) so that it can be self-serve.
```[tasklist]
### Tasks
- [ ] Update the Newsletters Tool to allow configuring the page
- [ ] Surface the result in the Newsletters API
- [ ] Update frontend to consume and store the config, and send it to DCAR
- [ ] Update DCAR to use the config from frontend, replacing the hardcoded version
```

**Comment by shesah** [comment]
Calvin will speak to Max about timelines for this. we will re-triage

**Comment by CDicksonG** [comment]
Is this being secretly done by David Blatcher? Who knows?
