### ISSUE TITLE
[Epic]: New Document Outline Designs

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9193]
Figma: https://www.figma.com/file/xPr2tZZger7pszcO075tAQ/New-Formats---April-23?type=design&node-id=2001-2452&mode=design&t=uZREUy2cpReYOwlP-0

This covers headings, dropcaps and adding some spacing above the first paragraph in an article.

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/9194
- [ ] https://github.com/guardian/dotcom-rendering/issues/9284
- [ ] https://github.com/guardian/dotcom-rendering/issues/9285
- [ ] https://github.com/guardian/dotcom-rendering/issues/11014
- [ ] https://github.com/guardian/dotcom-rendering/issues/9212
- [ ] https://github.com/guardian/dotcom-rendering/issues/11049
- [ ] https://github.com/guardian/dotcom-rendering/issues/11051
- [ ] Add "regular" font to DCR
- [ ] https://github.com/guardian/dotcom-rendering/issues/11202
```

**Comment by alinaboghiu** [comment]
https://www.figma.com/file/xPr2tZZger7pszcO075tAQ/New-Formats---April-23?type=design&node-id=2001-2452&mode=design&t=uZREUy2cpReYOwlP-0
