### ISSUE TITLE
Document Outline: Authoritative

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9194]
This captures headings and dropcaps that have an "authoritative" style. These changes should go out together (either in a single PR, or a single feature switch) to create a consistent design update. The list of tasks is here for quick reference and full descriptions can be found below.

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/10939
- [ ] Headings: Clear, `ArticleDisplay.Immersive`
- [ ] Headings: Stand-out, `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`
- [ ] Headings: Stand-out, `ArticleDisplay.Immersive`
- [ ] Dropcaps: `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`
- [ ] Dropcaps: `ArticleDisplay.Immersive`
```

## Headings

<details>
<summary>

### Clear, `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`

</summary>

The list of formats that should have an "authoritative clear" heading design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 24px
* font-weight: regular
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 2px

Using Source, the typography API call would be:

```ts
headline.xsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 28px
* font-weight: regular
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 4px

Using Source, the typography API call would be:

```ts
headline.small({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

</details>

<details>
<summary>

### Clear, `ArticleDisplay.Immersive` 

</summary>

The list of formats that should have an "authoritative clear" heading design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 28px
* font-weight: regular
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 2px

Using Source, the typography API call would be:

```ts
headline.small({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 34px
* font-weight: regular
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 4px

Using Source, the typography API call would be:

```ts
headline.medium({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

</details>

<details>
<summary>

### Stand-out, `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`

</summary>

The list of formats that should have an "authoritative stand-out" heading design must be the following `ArticleDesign`s:

- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 24px
* font-weight: regular
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 2px

Using Source, the typography API call would be:

```ts
headline.xsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 28px
* font-weight: regular
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 4px

Using Source, the typography API call would be:

```ts
headline.small({ fontWeight: 'regular', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>

<details>
<summary>

### Stand-out, `ArticleDisplay.Immersive` 

</summary>

The list of formats that should have an "authoritative stand-out" heading design must be the following `ArticleDesign`s:

- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 28px
* font-weight: regular
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 2px

Using Source, the typography API call would be:

```ts
headline.small({ fontWeight: 'regular', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 34px
* font-weight: regular
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 4px

Using Source, the typography API call would be:

```ts
headline.medium({ fontWeight: 'regular', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>

## Dropcaps

<details>
<summary>

### `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`

</summary>

The list of formats that should have an "authoritative" dropcap design must be the following `ArticleDesign`s:

- `ArticleDesign.Comment`

* font: GuardianHeadline
* font-size: 112px
* font-weight: light
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500

Using Source, the typography API call would be:

```ts
font-family: ${fonts.headline};
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>

<details>
<summary>

### `ArticleDisplay.Immersive` 

</summary>

The list of formats that should have an "authoritative" dropcap design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`
- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`

* font: GuardianHeadline
* font-size: 112px
* font-weight: light
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500

Using Source, the typography API call would be:

```ts
font-family: ${fonts.headline};
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>
