### ISSUE TITLE
[Epic]: New Dropcap Designs

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9197]
```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/9198
- [ ] https://github.com/guardian/dotcom-rendering/issues/9199
- [ ] https://github.com/guardian/dotcom-rendering/issues/9201
```

**Comment by ioannakok** [comment]
Covered by #9193
