### ISSUE TITLE
Header: Authoritative

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#9256]
This captures headlines, standfirsts and bylines that have an "authoritative" style. These changes should go out together (either in a single PR, or a single feature switch) to create a consistent design update. The list of tasks is here for quick reference and full descriptions can be found below.

Designs:
https://www.figma.com/file/xPr2tZZger7pszcO075tAQ/New-Formats---April-23?type=design&node-id=2144%3A46834&mode=dev

```[tasklist]
### Tasks
- [ ] Headline Clear - `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`
- [ ] Headline Stand-out  - `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`
- [ ] Headline Clear  - `ArticleDisplay.Immersive`
- [ ] Headline Stand-out  - `ArticleDisplay.Immersive`
- [ ] Standfirst - `ArticleDisplay.Standard`
- [ ] Standfirst - `ArticleDisplay.Showcase`
- [ ] Standfirst - `ArticleDisplay.Immersive`
- [ ] Byline - `ArticleDesign.Comment` / `ArticleDesign.Editorial`
```

## Headline

<details>
<summary>

### Clear - `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`

</summary>

The list of formats that should have an "authoritative clear" headline design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 28px
* font-weight: light
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing below: 28px

Using Source, the typography API call would be:

```ts
headline.small({ fontWeight: 'light', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 34px
* font-weight: light
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing below: 34px

Using Source, the typography API call would be:

```ts
headline.medium({ fontWeight: 'light', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

</details>
<details>
<summary>

### Stand-out - `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`

</summary>

The list of formats that should have an "authoritative stand-out" headline design must be the following `ArticleDesign`s:

- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 28px
* font-weight: light
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing below: 28px

Using Source, the typography API call would be:

```ts
headline.small({ fontWeight: 'light', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 34px
* font-weight: light
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing below: 34px

Using Source, the typography API call would be:

```ts
headline.medium({ fontWeight: 'light', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>
<details>
<summary>

### Clear - `ArticleDisplay.Immersive`

</summary>

The list of formats that should have an "authoritative clear" headline design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 34px
* font-weight: light
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing below: 28px

Using Source, the typography API call would be:

```ts
headline.medium({ fontWeight: 'light', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 50px
* font-weight: light
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing below: 34px

Using Source, the typography API call would be:

```ts
headline.xlarge({ fontWeight: 'light', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

</details>
<details>
<summary>

### Stand-out - `ArticleDisplay.Immersive`

</summary>

The list of formats that should have an "authoritative stand-out" headline design must be the following `ArticleDesign`s:

- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 34px
* font-weight: light
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing below: 28px

Using Source, the typography API call would be:

```ts
headline.medium({ fontWeight: 'light', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 50px
* font-weight: light
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing below: 34px

Using Source, the typography API call would be:

```ts
headline.xlarge({ fontWeight: 'light', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>

## Standfirst

<details>
<summary>

### `ArticleDisplay.Standard`

</summary>

The list of formats that should have an "authoritative" standfirst design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`
- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 17px
* font-weight: regular
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing below: 8px
* max-width: 90%

Using Source, the typography API call would be:

```ts
headline.xxxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 20px
* font-weight: regular
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing below: 8px
* max-width: minimum of 496px or 80% (possibly css [`min()`](https://developer.mozilla.org/en-US/docs/Web/CSS/min) function)

Using Source, the typography API call would be:

```ts
headline.xxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

</details>
<details>
<summary>

### `ArticleDisplay.Showcase`

</summary>

The list of formats that should have an "authoritative" standfirst design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`
- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 17px
* font-weight: regular
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing below: 8px

Using Source, the typography API call would be:

```ts
headline.xxxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 20px
* font-weight: regular
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing below: 14px

Using Source, the typography API call would be:

```ts
headline.xxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

</details>

<details>
<summary>

### `ArticleDisplay.Immersive`

</summary>

The list of formats that should have an "authoritative" standfirst design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`
- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 20px
* font-weight: regular
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing below: 24px

Using Source, the typography API call would be:

```ts
headline.xxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 24px
* font-weight: regular
* lightmode colour: neutral[7]
* darkmode colour: neutral[60]
* spacing below: 24px

Using Source, the typography API call would be:

```ts
headline.xsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

</details>

## Byline

<details>
<summary>

### `ArticleDesign.Comment` / `ArticleDesign.Editorial`

</summary>

#### On all breakpoints

* font: GuardianHeadline
* font-size: 34px
* font-weight: light
* lightmode colour: pillar colour 400
* darkmode colour: pillar colour 500

Using Source, the typography API call would be:

```ts
headline.medium({ fontWeight: 'light', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[400]};
`;
```

</details>

**Comment by HarryFischer** [comment]
Just to say, I added to Figma/and the ticket above the details around the font sizes on Immersive article. Sorry for missing this detail initially

**Comment by georgeblahblah** [comment]
Done in https://github.com/guardian/dotcom-rendering/pull/11257
