### ISSUE TITLE
Document Outline: Soft

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9285]
This captures headings and dropcaps that have a "soft" style. These changes should go out together (either in a single PR, or a single feature switch) to create a consistent design update. The list of tasks is here for quick reference and full descriptions can be found below.

```[tasklist]
### Tasks
- [ ] Headings: Clear, `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`
- [ ] Headings: Clear, `ArticleDisplay.Immersive`
- [ ] Headings: Stand-out, `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`
- [ ] Headings: Stand-out, `ArticleDisplay.Immersive`
- [ ] Dropcaps: `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`
- [ ] Dropcaps: `ArticleDisplay.Immersive`
```

## Headings

<details>
<summary>

### Stand-out, `ArticleDisplay.Standard` / `ArticleDisplay.Showcase`

</summary>

The list of formats that should have a "neutral stand-out" heading design must be the following `ArticleDesign`s:

- `ArticleDesign.Feature`
- `ArticleDesign.Interview`
- `ArticleDesign.Recipe`
- `ArticleDesign.Review`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 24px
* font-weight: bold
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 2px

Using Source, the typography API call would be:

```ts
headline.xsmall({ fontWeight: 'bold', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 28px
* font-weight: bold
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 4px

Using Source, the typography API call would be:

```ts
headline.small({ fontWeight: 'bold', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>

<details>
<summary>

### Stand-out, `ArticleDisplay.Immersive` 

</summary>

The list of formats that should have an "authoritative stand-out" heading design must be the following `ArticleDesign`s:

- `ArticleDesign.Feature`
- `ArticleDesign.Interview`
- `ArticleDesign.Recipe`
- `ArticleDesign.Review`

#### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 28px
* font-weight: bold
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 2px

Using Source, the typography API call would be:

```ts
headline.small({ fontWeight: 'bold', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

#### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 34px
* font-weight: bold
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500
* spacing above: 8px (in addition to the normal paragraph spacing)
* spacing below: 4px

Using Source, the typography API call would be:

```ts
headline.medium({ fontWeight: 'bold', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>

## Dropcaps

<details>
<summary>

### `ArticleDisplay.Standard` / `ArticleDisplay.Showcase` / `ArticleDisplay.Immersive`

</summary>

The list of formats that should have a "soft" dropcap design must be the following `ArticleDesign`s:

- `ArticleDesign.Feature`
- `ArticleDesign.Interview`
- `ArticleDesign.Recipe`
- `ArticleDesign.Review`

* font: GuardianHeadline
* font-size: 112px
* font-weight: bold
* lightmode colour: pillar colour 200
* darkmode colour: pillar colour 500

Using Source, the typography API call would be:

```ts
font-family: ${fonts.headline};
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>
