### ISSUE TITLE
Pullquote: Authoritative

### ISSUE THREAD

**Issue by sophie-macmillan** [guardian/dotcom-rendering#9298]
This captures pullquotes that have an "authoritative" style. These changes should go out together (either in a single PR, or a single feature switch) to create a consistent design update. The list of tasks is here for quick reference and full descriptions can be found below.

https://www.figma.com/file/xPr2tZZger7pszcO075tAQ/New-Formats---April-23?type=design&node-id=2002-32607&mode=design&t=fQ2u2Xgcc2ZTmwVT-4

```[tasklist]
### Tasks
- [x] PullQuote Role: Inline, Clear
- [x] PullQuote Role: Showcase, Clear
- [x] PullQuote Role: Supporting, Clear
- [x] PullQuote Role: Inline, Standout
- [x] PullQuote Role: Showcase, Standout
- [x] PullQuote Role: Supporting, Standout
```

<details>
<summary>

## Role: Inline, Clear

</summary>

The list of formats that should have an "authoritative" inline, clear pullquote design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`

### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 20px
* font-weight: regular
* lightmode font colour: neutral[7]
* darkmode font colour: neutral[60]
* lightmode svg colour: neutral[46]
* darkmode svg colour: neutral[60]
* spacing above: 14px
* spacing below: 14px
* spacing between svg and text: 4px
* max-width: 90%

Using Source, the typography API call would be:

```ts
headline.xxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 24px
* font-weight: regular
* lightmode font colour: neutral[7]
* darkmode font colour: neutral[60]
* lightmode svg colour: neutral[46]
* darkmode svg colour: neutral[60]
* spacing above: 14px
* spacing below: 14px
* spacing between svg and text: 4px
* max-width: min(80%, 496px)

Using Source, the typography API call would be:

```ts
headline.xsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

</details>

<details>
<summary>

## Role: Inline, Standout

</summary>

The list of formats that should have an "authoritative" inline, standout pullquote design must be the following `ArticleDesign`s:

- `ArticleDesign.Editorial`
- `ArticleDesign.Comment`

### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 20px
* font-weight: regular
* lightmode font colour: pillar colour 200
* darkmode font colour: pillar colour 500
* lightmode svg colour: pillar colour 200
* darkmode svg colour: pillar colour 500
* spacing above: 14px
* spacing below: 14px
* spacing between svg and text: 4px
* max-width: 90%

Using Source, the typography API call would be:

```ts
headline.xxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and an example of the colour change would be:
```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 24px
* font-weight: regular
* lightmode font colour: pillar colour 200
* darkmode font colour: pillar colour 500
* lightmode svg colour: pillar colour 200
* darkmode svg colour: pillar colour 500
* spacing above: 14px
* spacing below: 14px
* spacing between svg and text: 4px
* max-width: min(80%, 496px)

Using Source, the typography API call would be:

```ts
headline.xsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and an example of the colour change would be:
```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>

<details>
<summary>

## Role: Showcase, Clear

</summary>

The list of formats that should have an "authoritative" showcase, clear pullquote design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`

### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 24px
* font-weight: regular
* lightmode font colour: neutral[7]
* darkmode font colour: neutral[60]
* lightmode svg colour: neutral[46]
* darkmode svg colour: neutral[60]
* spacing above: 14px
* spacing below: 14px
* spacing between svg and text: 4px
* max-width: 90%

Using Source, the typography API call would be:

```ts
headline.xxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 28px
* font-weight: regular
* lightmode font colour: neutral[7]
* darkmode font colour: neutral[60]
* lightmode svg colour: neutral[46]
* darkmode svg colour: neutral[60]
* spacing above: 14px
* spacing below: 14px
* spacing between svg and text: 4px
* max-width: min(80%, 496px)

Using Source, the typography API call would be:

```ts
headline.xsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

</details>

<details>
<summary>

## Role: Showcase, Standout

</summary>

The list of formats that should have an "authoritative" showcase, standout pullquote design must be the following `ArticleDesign`s:

- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`

### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 24px
* font-weight: regular
* lightmode font colour: pillar colour 200
* darkmode font colour: pillar colour 500
* lightmode svg colour: pillar colour 200
* darkmode svg colour: pillar colour 500
* spacing above: 14px
* spacing below: 14px
* spacing between svg and text: 4px
* max-width: 90%

Using Source, the typography API call would be:

```ts
headline.xxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 28px
* font-weight: regular
* lightmode font colour: pillar colour 200
* darkmode font colour: pillar colour 500
* lightmode svg colour: pillar colour 200
* darkmode svg colour: pillar colour 500
* spacing above: 14px
* spacing below: 14px
* spacing between svg and text: 4px
* max-width: min(80%, 496px)

Using Source, the typography API call would be:

```ts
headline.xsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>

<details>
<summary>

## Role: Supporting, Clear

</summary>

The list of formats that should have an "authoritative" supporting, clear pullquote design must be the following `ArticleDesign`s:

- `ArticleDesign.Obituary`

### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 20px
* font-weight: regular
* lightmode font colour: neutral[7]
* darkmode font colour: neutral[60]
* lightmode svg colour: neutral[46]
* darkmode svg colour: neutral[60]
* padding: 10px
* margin: 10px
* spacing between svg and text: 4px
* max-width: 40%
* Should be inline

Using Source, the typography API call would be:

```ts
headline.xxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 20px
* font-weight: regular
* lightmode font colour: neutral[7]
* darkmode font colour: neutral[60]
* lightmode svg colour: neutral[46]
* darkmode svg colour: neutral[60]
* padding: 10px
* margin: 10px
* spacing between svg and text: 4px
* width: 240px
* Should be slightly left aligned

Using Source, the typography API call would be:

```ts
headline.xxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and colours from `palette.neutral`.

</details>

<details>
<summary>

## Role: Supporting, Standout

</summary>

The list of formats that should have an "authoritative" supporting, standout pullquote design must be the following `ArticleDesign`s:

- `ArticleDesign.Comment`
- `ArticleDesign.Editorial`

### Until Tablet Breakpoint

* font: GuardianHeadline
* font-size: 20px
* font-weight: regular
* lightmode font colour: pillar colour 200
* darkmode font colour: pillar colour 500
* lightmode svg colour: pillar colour 200
* darkmode svg colour: pillar colour 500
* padding: 10px
* margin: 10px
* spacing between svg and text: 4px
* max-width: 40%
* Should be inline
* Should take background of article

Using Source, the typography API call would be:

```ts
headline.xxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

### From Tablet Breakpoint

* font: GuardianHeadline
* font-size: 20px
* font-weight: regular
* lightmode font colour: pillar colour 200
* darkmode font colour: pillar colour 500
* lightmode svg colour: pillar colour 200
* darkmode svg colour: pillar colour 500
* padding: 10px
* margin: 10px
* spacing between svg and text: 4px
* width: 240px
* Should be slightly left aligned
* Should take background of article

Using Source, the typography API call would be:

```ts
headline.xxsmall({ fontWeight: 'regular', lineHeight: 'tight' })
```

and an example of the colour change would be:

```ts
const styles = css`
  color: ${palette.news[200]};
`;
```

</details>

**Comment by shesah** [comment]
To be picked up after health week
