### ISSUE TITLE
[Epic]: Bugs from DCAR release to Beta for first production release

### ISSUE THREAD

**Issue by alinaboghiu** [guardian/dotcom-rendering#9301]
```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/9250
- [ ] https://github.com/guardian/dotcom-rendering/issues/9279
- [ ] https://github.com/guardian/dotcom-rendering/pull/9701
```

See other bugs from Beta that aren't prioritised for this release in https://github.com/guardian/dotcom-rendering/issues/9658
