### ISSUE TITLE
Stop using `yarn@1` in DCR

### ISSUE THREAD

**Issue by sndrs** [guardian/dotcom-rendering#9421]
Yarn 1 is 6 years old and [went into maintenance mode 3.5 years ago](https://dev.to/arcanis/introducing-yarn-2-4eh1#what-will-happen-to-the-legacy-codebase).

it also hoists dependencies, which makes it very hard to know which version of a dep you'll be using, and makes transitive deps available to everyone.

we should move to a more modern package manager, in particular one that doesn't need to hoist deps, like pnpm or yarn 4

```[tasklist]
### Tasks
- [x] investigate `yarn@3`/`yarn@4`
- [ ] https://github.com/yarnpkg/berry/issues/5165
- [ ] https://github.com/guardian/dotcom-rendering/pull/9400
- [ ] https://github.com/guardian/commercial/pull/1133
- [ ] https://github.com/guardian/dotcom-rendering/pull/9466
- [ ] https://github.com/guardian/dotcom-rendering/pull/9476
- [ ] https://github.com/guardian/dotcom-rendering/pull/9576
- [ ] https://github.com/guardian/dotcom-rendering/pull/9565
- [ ] https://github.com/guardian/dotcom-rendering/pull/9562
- [ ] https://github.com/guardian/dotcom-rendering/pull/9559
- [ ] https://github.com/guardian/dotcom-rendering/pull/9610
```
