### ISSUE TITLE
DCR Dev Server Refactor

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9493]
Making it easier to use the DCR dev server, and in particular improving how examples of articles with different formats and features are surfaced.

```[tasklist]
### Tasks
- [x] Add TS checking
- [x] Add articles to the list in browsers where the clipboard feature isn't supported
- [ ] Refactor the article lists
- [ ] Add format and features to article representations
```
