### ISSUE TITLE
Check with design about one off colours in palette

### ISSUE THREAD

**Issue by sophie-macmillan** [guardian/dotcom-rendering#9531]
While implementing dark mode, we've been copying across and updating the palette. We've come across some one off colours that we should check. Are these intending, or can we update them to use the standard sourcePalette?

```[tasklist]
### Tasks
- [x] [Headline border for liveblogs](https://github.com/guardian/dotcom-rendering/blob/af1661390af82d42da54a67203403d14635046d6/dotcom-rendering/src/palette.ts#L976-L977) `currently rgba(255,255,255, 0.2)`
- [x] [Headline border for deadblogs](https://github.com/guardian/dotcom-rendering/blob/af1661390af82d42da54a67203403d14635046d6/dotcom-rendering/src/palette.ts#L978-L979) `currently #CDCDCD`
- [x] [Standfirst border for liveblogs](https://github.com/guardian/dotcom-rendering/blob/af1661390af82d42da54a67203403d14635046d6/dotcom-rendering/src/palette.ts#L1945-L1946) `currently rgba(255,255,255, 0.2)`
- [x] [Standfirst border for deadblogs](https://github.com/guardian/dotcom-rendering/blob/af1661390af82d42da54a67203403d14635046d6/dotcom-rendering/src/palette.ts#L1947-L1948) `currently #BDBDBD`
```

**Comment by HarryFischer** [comment]
Headline border for liveblog: `return transparentColour(sourcePalette.neutral[100], 0.2);`
Headline border for liveblog: neutral.86 (#dcdcdc) 
Headline border for deadblog: `return transparentColour(sourcePalette.neutral[100], 0.2);`
Standfirst border for deadblog: neutral.86 (#dcdcdc)

**Comment by georgeblahblah** [comment]
we are moving this to backlog in planning because liveblogs&deadblogs are not prioritised for the first production release

**Comment by jamesmockett** [comment]
In addition to `#d9edf6` for match stats background (also used in a number of interactives) we also have the following hardcoded 'one-off' colours in the palette:

- `#f2e8e6` → rich link background (light), affiliate disclaimer background (light) and expandable atom background (light) (all for analysis design only)
- `#e9d9d5` → rich link background hover (light) and affiliate disclaimer background hover (light) (all for analysis design only)
- `#f5f2f0` → code block background (light)
- `#606060` → stacked progress background (dark)

There's also `rgba(250, 250, 250, 0.6)` which was very recently added for the Fairground highlights container, but is very specific as it defines the midpoint of a background gradient so cannot be replaced with a colour from Source.
