### ISSUE TITLE
[Epic] Support mobile articles with discussion

### ISSUE THREAD

**Issue by sophie-macmillan** [guardian/dotcom-rendering#9667]
We are currently not supporting articles with Comments in AR/DCAR.

They are filtered out in MAPI, and we have a `isWeb` condition as well.

We want to support articles with comments eventually though, so we'll have to do the following

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/9882
- [ ] Remove the isWeb condition across layouts
- [ ] Update the filter in MAPI (https://github.com/guardian/mobile-apps-api/blob/6707639a7a78a4fc90448eb760f02e2e928c4501/common-play/src/main/scala/data/DcrSupportUtils.scala#L44)
- [ ] https://github.com/guardian/dotcom-rendering/issues/9869
- [ ] https://github.com/guardian/dotcom-rendering/issues/9871
- [ ] Implement bridget services for discussion in the native layer
```

**Comment by shesah** [comment]
@mxdvl could you just do an audit on this epic and move any outstanding issues to the new epic please?

**Comment by mxdvl** [comment]
Duplicate of https://github.com/guardian/dotcom-rendering/issues/8745
