### ISSUE TITLE
Filter out from DCAR interactive elements that are currently unsupported in AR

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#9762]
We should filter out the following elements from being rendered in DCAR as they are currently unsupported in AR. Example articles where these can be found are linked next to each element. Please check the AR versions of these articles for reference.

```[tasklist]
### Tasks
- [x] InteractiveContentsBlockElement: https://www.theguardian.com/world/2020/mar/28/life-after-coronavirus-panic-buying-cocaine-drug-dealer-spaceman-therapist
- [x] QAAtom: https://www.theguardian.com/technology/2019/dec/17/best-smartphone-2019-iphone-oneplus-samsung-and-huawei-compared-and-ranked
- [x] GuideAtomBlockElement: https://www.theguardian.com/world/2020/may/07/revealed-the-secret-report-that-gave-ministers-warning-of-care-home-coronavirus-crisis
- [x] InteractiveAtomBlockElement: https://www.theguardian.com/world/2020/mar/31/view-from-nhs-staff-in-frontline-of-battle-against-coronavirus
- [x] ExplainerAtomBlockElement: https://www.theguardian.com/books/2020/may/20/poems-to-get-us--carol-ann-duffy-ella-frears
- [x] QuizAtomBlockElement: https://www.theguardian.com/sport/2020/dec/04/sports-quiz-week-hat-tricks-histrionics-historical-hostilities
- [x] CodeBlockElement: https://www.theguardian.com/info/2021/jan/26/how-we-made-typerighter-the-guardians-style-guide-checker
- [x] AudioAtomBlockElement: https://www.theguardian.com/world/2022/apr/05/tuesday-briefing-atrocities-ukraine
```

**Comment by abeddow91** [comment]
As these don't exist in apps rendering, we won't currently have dark mode designs for these. @HarryFischer - would you be able to stick these on the designs team todo list? We'll be filtering them out for now so there's not an immediate rush.

**Comment by abeddow91** [comment]
Fixed in https://github.com/guardian/mobile-apps-api/pull/2844
