### ISSUE TITLE
Filter Out Features That Do Not Support Dark Mode

### ISSUE THREAD

**Issue by ioannakok** [guardian/dotcom-rendering#9772]
```[tasklist]
### Tasks
- [ ] https://github.com/guardian/dotcom-rendering/issues/9830
- [x] Table of contents: https://www.theguardian.com/world/2020/mar/28/life-after-coronavirus-panic-buying-cocaine-drug-dealer-spaceman-therapist
- [x] Code: https://www.theguardian.com/info/2021/jan/26/how-we-made-typerighter-the-guardians-style-guide-checker
- [x] Q&A atom: https://www.theguardian.com/technology/2019/dec/17/best-smartphone-2019-iphone-oneplus-samsung-and-huawei-compared-and-ranked
- [x] Guide atom: https://www.theguardian.com/travel/2019/oct/12/20-best-alps-ski-resorts-by-train-rail-france-switzerland-austria-italy
- [x] Interactive atom: https://www.theguardian.com/world/2020/mar/31/view-from-nhs-staff-in-frontline-of-battle-against-coronavirus
- [x] Explainer atom: https://www.theguardian.com/books/2020/may/20/poems-to-get-us--carol-ann-duffy-ella-frears
- [x] Quiz atom: https://www.theguardian.com/sport/2020/dec/04/sports-quiz-week-hat-tricks-histrionics-historical-hostilities
- [x] Audio atom: https://www.theguardian.com/world/2022/apr/05/tuesday-briefing-atrocities-ukraine
```

**Comment by JamieB-gu** [comment]
Atoms filtered out here: https://github.com/guardian/mobile-apps-api/pull/2844

**Comment by abeddow91** [comment]
closed as duplicate of https://github.com/guardian/dotcom-rendering/issues/9762
