### ISSUE TITLE
Java 11+

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9890]
[AWS is deprecating `java8` runtime](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) so we have to update our lambdas to use `java11`

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/frontend-lambda/issues/57
- [ ] https://github.com/guardian/frontend-lambda/issues/55
- [ ] https://github.com/guardian/skimlinks-lambda/issues/13
```

[Similar upgrade PR](https://github.com/guardian/platform/pull/1510) for security-groups-update

**Comment by ioannakok** [comment]
The lambdas have been upgraded to `java11`. Created a follow-up ticket to clean up whatever lambdas we don't need: https://github.com/guardian/dotcom-rendering/issues/10000
