### ISSUE TITLE
Migrate DCR To DevX Logs

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/dotcom-rendering#9912]
Our current logging integration is not working as expected[^1][^2] and DevX now recommend using `devx-logs` for log shipping.

We're currently doing a similar migration for `frontend` in #9825 and the steps are likely similar; there are several links to relevant PRs in that issue.

```[tasklist]
### Tasks
- [ ] Add `cdk-base` to AMI recipe for DCR: https://github.com/guardian/amigo/tree/main/roles/cdk-base
- [ ] Make sure DCR logs appear in the place `devx-logs` expects: https://github.com/guardian/devx-logs/tree/main/ec2
- [ ] Remove the kinesis logging configuration
```

The current kinesis-based logging configuration is mainly in `userData.ts`:

https://github.com/guardian/dotcom-rendering/blob/ab07e180f2fb414d727e4972f2edfd8423b187ea/dotcom-rendering/cdk/lib/userData.ts#L18

https://github.com/guardian/dotcom-rendering/blob/ab07e180f2fb414d727e4972f2edfd8423b187ea/dotcom-rendering/cdk/lib/userData.ts#L32-L33

https://github.com/guardian/dotcom-rendering/blob/ab07e180f2fb414d727e4972f2edfd8423b187ea/dotcom-rendering/cdk/lib/userData.ts#L37

[^1]: https://github.com/guardian/dotcom-rendering/issues/9846#issuecomment-1856168265
[^2]: #9908
